### ISSUE TITLE
Sample运行不了

### ISSUE THREAD

**Issue by huzhenjie** [wequick/Small#112]
```
net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: Thread-2933
                                                                           Process: net.wequick.example.small, PID: 27013
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Collection java.util.concurrent.ConcurrentHashMap.values()' on a null object reference
                                                                               at net.wequick.small.ApkBundleLauncher$ResourcesMerger.merge(ApkBundleLauncher.java:541)
                                                                               at net.wequick.small.ApkBundleLauncher.postSetUp(ApkBundleLauncher.java:342)
                                                                               at net.wequick.small.Bundle.loadBundles(Bundle.java:533)
                                                                               at net.wequick.small.Bundle.loadManifest(Bundle.java:201)
                                                                               at net.wequick.small.Bundle.loadBundles(Bundle.java:183)
                                                                               at net.wequick.small.Bundle.access$000(Bundle.java:63)
                                                                               at net.wequick.small.Bundle$LoadBundleThread.run(Bundle.java:504)
```

**Comment by galenlin** [comment]
编译了没有

**Comment by tcking** [comment]
原因应该是这样的，在Bound.load的时候回会调用`preloadBundle`判断当前的bound是否支持，如果不支持则不会加载此bound，在此情况下`sLoadedApks`就是null从而导致NP，回归来看`preloadBundle`中判断是否支持的条件是`packageName.contains("." + type + ".")` 其中type为`app`或`lib`，要fix当前问题只需要检查插件的包名是否符合这个约定，即如果带有资源的插件，包名必须包含`app`,不带资源的插件报名必须包含`lib`

**Comment by galenlin** [comment]
@tcking 对的，出现这个报错就是说明app/smallLibs下还没有正常编译的插件so

**Comment by wuruize** [comment]
@tcking @galenlin 肯定是编译了的。我同样有这个问题/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: Thread-122
                                                                         Process: net.wequick.example.small, PID: 2923
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Collection java.util.concurrent.ConcurrentHashMap.values()' on a null object reference
                                                                             at net.wequick.small.ApkBundleLauncher$ResourcesMerger.merge(ApkBundleLauncher.java:541)
                                                                             at net.wequick.small.ApkBundleLauncher.postSetUp(ApkBundleLauncher.java:342)
                                                                             at net.wequick.small.Bundle.loadBundles(Bundle.java:532)
                                                                             at net.wequick.small.Bundle.loadManifest(Bundle.java:196)
                                                                             at net.wequick.small.Bundle.loadBundles(Bundle.java:178)
                                                                             at net.wequick.small.Bundle.access$000(Bundle.java:63)
                                                                             at net.wequick.small.Bundle$LoadBundleThread.run(Bundle.java:503)

不过用的是模拟器跑的

另外这个demo是这里提供的包名，肯定是遵守相关协定的。

**Comment by tcking** [comment]
模拟器的abi是x86的，目前默认编译的so放在了armlib下，可以把armlib改名为x86或修改gradle的脚本输出到x86目录

**Comment by wuruize** [comment]
@tcking 对的。
