### ISSUE TITLE
插架间资源依赖 问题

### ISSUE THREAD

**Issue by skylz** [wequick/Small#119]
我自己写了两个插架，A，和B，B依赖A，引用A里边的资源（用@A_package:type/resoucename 方式）和class，然后重写了aapt（基于23.0.2）用于资源id 分段，B打包的时候加上参数-I A，然后把两个包 放到lib/armbi下，用正常的gradle脚本（单纯执行installDebug）打包，android 5.0以上可以正常运行（只测试了activity），5.0以下资源会找不到，报错
android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x7/d=0x65040000 a=-1}
                                                                                  at android.content.res.Resources.loadDrawable(Resources.java:2119)
                                                                                  at android.content.res.Resources.loadDrawable(Resources.java:2072)
                                                                                  at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                                  at android.view.View.<init>(View.java:3558)

，但是我用getResouce().getColor(getIndentify(资源name，type，A的package))方式在B的activity里边是可以得到资源的。因为对底层不了解，不知道5.0以上和一下的区别，请问大神这个问题怎么解决，

**Comment by galenlin** [comment]
编译跟代码是配合的，不好确定你的问题。

检查资源是否编译正确可以使用命令：

```bash
aapt d resources B.apk
```

搜索`0x65040000`看是什么类型的资源。

**Comment by skylz** [comment]
aapt d resources B.apk没有问题 ，0x65040000是一个color ,因为small我看每个插架都有compile lib.style，想把公共资源也打成一个插架，这样如果插架多的话，可以减少重复资源

**Comment by skylz** [comment]
这个问题是因为ResourceTypes.cpp 里边TYPE_DYNAMIC_REFERENCE，type值 是0x7，这个东西是5.0以后有的，所以android:background(0x010100d4)=(type 0x7)0x65040000 在5.0以下有问题。如果是TYPE_REFERENCE 编译结果是android:background(0x010100d4)=@0x65040000 ，5.0以下只识别这种方式
