### ISSUE TITLE
新建项目运行异常，直接在demo里该是可以运行的

### ISSUE THREAD

**Issue by Phoon-Think** [wequick/Small#123]
FATAL EXCEPTION: main
                                                 Process: com.bjdv.mos, PID: 7638
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bjdv.mos/net.wequick.small.A}: android.view.InflateException: Binary XML file line #12: Error inflating class android.widget.TextView
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class android.widget.TextView
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
                                                     at android.app.Activity.setContentView(Activity.java:1929)
                                                     at com.bjdv.mos.app.home.MainActivity.onCreate(MainActivity.java:11)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:142)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by galenlin** [comment]
版本是否是最新的：
* gradle-small: 0.6.0
* small { aarVersion = '0.9.0' }

**Comment by Phoon-Think** [comment]
是最新的
small {
    strictSplitResources = false
    aarVersion = '0.9.0'
}
