### ISSUE TITLE
Android Sample运行错误

### ISSUE THREAD

**Issue by dieyidezui** [wequick/Small#124]
按照引导依次buildLib,buildBundle,run app，运行的时候就crash了。

05-03 02:16:24.468 1217-1232/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: Thread-96
java.lang.NullPointerException
       at net.wequick.small.ApkBundleLauncher$ResourcesMerger.merge(ApkBundleLauncher.java:541)
       at net.wequick.small.ApkBundleLauncher.postSetUp(ApkBundleLauncher.java:342)
       at net.wequick.small.Bundle.loadBundles(Bundle.java:533)
       at net.wequick.small.Bundle.loadManifest(Bundle.java:201)
       at net.wequick.small.Bundle.loadBundles(Bundle.java:183)
       at net.wequick.small.Bundle.access$000(Bundle.java:63)
       at net.wequick.small.Bundle$LoadBundleThread.run(Bundle.java:504)

**Comment by dieyidezui** [comment]
已经解决了，是genymotion虚拟机的问题，真机可以使用

**Comment by galenlin** [comment]
@dieyidezui 模拟器上需要把`app/smallLibs/armeabi`改为`app/smallLibs/x86`

**Comment by dieyidezui** [comment]
@galenlin 3Q

**Comment by offbye** [comment]
今天也碰到这个问题了，能不能针对genymotion 模拟器加个build参数呢？

**Comment by galenlin** [comment]
@offbye 编译的时候加上 -Dbundle.arch=x86可以指定输出的so路径
