### ISSUE TITLE
新建工程，在插件中使用了一张图片

### ISSUE THREAD

**Issue by limingwei234** [wequick/Small#137]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mwli.demo2/com.mwli.demo2.app.main.MainActivity}: android.view.InflateException: Binary XML file line #19: Error inflating class <unknown>
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:174)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                    at android.os.Looper.loop(Looper.java:222)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5484)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                 Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class <unknown>
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:347)
                                                                    at android.app.Activity.setContentView(Activity.java:1993)
                                                                    at com.mwli.demo2.app.main.MainActivity.onCreate(MainActivity.java:12)
                                                                    at android.app.Activity.performCreate(Activity.java:5463)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:160)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:174) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                    at android.os.Looper.loop(Looper.java:222) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5484) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:347) 
                                                                    at android.app.Activity.setContentView(Activity.java:1993) 
                                                                    at com.mwli.demo2.app.main.MainActivity.onCreate(MainActivity.java:12) 
                                                                    at android.app.Activity.performCreate(Activity.java:5463) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:160) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:174) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                    at android.os.Looper.loop(Looper.java:222) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5484) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                 Caused by: android.content.res.Resources$NotFoundException: File res/layout/abc_screen_toolbar.xml from drawable resource ID #0x77020002
                                                                    at android.content.res.Resources.loadDrawable(Resources.java:2294)
                                                                    at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                    at android.widget.ImageView.<init>(ImageView.java:129)
                                                                    at android.widget.ImageView.<init>(ImageView.java:119)
                                                                    at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:347) 
                                                                    at android.app.Activity.setContentView(Activity.java:1993) 
                                                                    at com.mwli.demo2.app.main.MainActivity.onCreate(MainActivity.java:12) 
                                                                    at android.app.Activity.performCreate(Activity.java:5463) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:160) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:174) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                    at android.os.Looper.loop(Looper.java:222) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5484) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                 Caused by: android.content.res.Resources$NotFoundException: File res/layout/abc_screen_toolbar.xml from xml type drawable resource ID #0x77020002
                                                                    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2560)
                                                                    at android.content.res.Resources.loadDrawable(Resources.java:2288)
                                                                    at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                                                                    at android.widget.ImageView.<init>(ImageView.java:129) 
                                                                    at android.widget.ImageView.<init>(ImageView.java:119) 
                                                                    at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:347) 
                                                                    at android.app.Activity.setContentView(Activity.java:1993) 
                                                                    at com.mwli.demo2.app.main.MainActivity.onCreate(MainActivity.java:12) 
                                                                    at android.app.Activity.performCreate(Activity.java:5463) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:160) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:174) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                    at android.os.Looper.loop(Looper.java:222) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5484) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                 Caused by: java.io.FileNotFoundException: res/layout/abc_screen_toolbar.xml
                                                                    at android.content.res.AssetManager.openXmlAssetNative(Native Method)
                                                                    at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:517)
                                                                    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2542)
                                                                    at android.content.res.Resources.loadDrawable(Resources.java:2288) 
                                                                    at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                                                                    at android.widget.ImageView.<init>(ImageView.java:129) 
                                                                    at android.widget.ImageView.<init>(ImageView.java:119) 
                                                                    at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
                                                                    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:347) 
                                                                    at android.app.Activity.setContentView(Activity.java:1993) 
                                                                    at com.mwli.demo2.app.main.MainActivity.onCreate(MainActivity.java:12) 
                                                                    at android.app.Activity.performCreate(Activity.java:5463) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:160) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:174) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                    at android.os.Looper.loop(Looper.java:222) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5484) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by galenlin** [comment]
感谢反馈，从你的描述无法定位问题，能否提供更多的信息，或者你的demo工程
