### ISSUE TITLE
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5

### ISSUE THREAD

**Issue by newyu** [wequick/Small#139]
FATAL EXCEPTION: main
 Process: com.example.mysmall, PID: 22734
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mysmall/net.wequick.small.A}: android.view.InflateException: Binary XML file line #14: Error inf
lating class android.widget.TextView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2392)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2443)
        at android.app.ActivityThread.access$800(ActivityThread.java:157)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5348)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
 Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class android.widget.TextView
        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:379)
        at android.app.Activity.setContentView(Activity.java:2021)
        at com.example.mysmall.app.main.MainActivity.onCreate(MainActivity.java:14)
        at android.app.Activity.performCreate(Activity.java:5451)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:148)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2346)
        ... 10 more
 Caused by: java.lang.reflect.InvocationTargetException:
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
        ... 24 more
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
        at android.content.res.AssetManager.getPooledString(AssetManager.java:288)
        at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:727)
        at android.content.res.TypedArray.getValueAt(TypedArray.java:712)
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:342)
        at android.widget.TextView.<init>(TextView.java:737)
        at android.widget.TextView.<init>(TextView.java:656)
        ... 27 more

**Comment by galenlin** [comment]
#62 貌似也是这个问题，你的设备型号版本麻烦发下。

**Comment by newyu** [comment]
m1 note Android 4.4.4  和 huawei p6-T00 Android 4.2.2都有这个问题

**Comment by galenlin** [comment]
@newyu 是否存在某个插件没有资源？即编译之后的压缩包里没有resources.arsc。
