### ISSUE TITLE
No resource found that matches the given name

### ISSUE THREAD

**Issue by a137235** [wequick/Small#144]
当一个lib引用另一个lib的时候，打包时就提示资源不存在。

**Comment by galenlin** [comment]
能否提供下示例工程，我调试下

**Comment by a137235** [comment]
怎么提供呀，这个没法上传呢

**Comment by a137235** [comment]
[http://download.csdn.net/detail/u014462114/9522763](url)

**Comment by galenlin** [comment]
已发现问题，`lib.*`之间暂不支持资源相互依赖。先绕开处理吧。

**Comment by a137235** [comment]
能不能帮忙解决下呢？如果绕开还是很麻烦的。

**Comment by galenlin** [comment]
过程有点复杂，短期内无法解决，预计需要1周+。

**Comment by a137235** [comment]
这样呀,看来也只有走弯路了。我还有个问题:Small内置的webview能不能扩展，就是界面控制还是由我们来弄？

**Comment by galenlin** [comment]
有哪些地方需要定制呢？可以举例吗

**Comment by a137235** [comment]
比如:加载进度,界面美化,操作控制等。

**Comment by galenlin** [comment]
目前有两个定制接口，应该可以满足大部分需求：

1. `Small.setWebViewClient` - 接收`onPageStarted`/`onPageFinished`/`onReceivedError`回调
2. `Small.registerJsHandler` - 自定义JS调用Native接口

你先看下，如果有哪里满足不了的跟我说下。

**Comment by a137235** [comment]
我还想定制下这个界面,就是将布局修改或者更改。

**Comment by alkaid** [comment]
@galenlin 额 我不是lib引用lib是 正常的app.xxx引用Lib为什么也提示找不到资源(res/raw)
`FATAL EXCEPTION: main
                                                                 Process: com.mykj.game.ddz, PID: 2228
                                                                 android.content.res.Resources$NotFoundException: File res/raw/key_click.mp3 from drawable resource ID #0x40050000
                                                                     at android.content.res.Resources.openRawResourceFd(Resources.java:2416)
                                                                     at android.media.MediaPlayer.create(MediaPlayer.java:992)
                                                                     at android.media.MediaPlayer.create(MediaPlayer.java:975)`

**Comment by galenlin** [comment]
raw的文件似乎处理方式不同，，

**Comment by hejie** [comment]
我的问题是 app 模块 依赖 lib.A模块  但lib.A 里面有layout文件 这样buildLib 不通过,现在lib.x 模块支持 layout文件?

**Comment by xiaobaDev** [comment]
@hejie app不能依赖lib框架。
