### ISSUE TITLE
新项目运行报错，You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by WayJ** [wequick/Small#145]
新建项目出现了一些问题，虽然解决了，还是想问下为什么会出现问题。
运行环境：华为8815，Android 4.1.2，API 16。
我的环境：jdk 1.8。
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    'com.android.support:appcompat-v7:23.3.0'

首先我按照sample新建了一个项目，有两个module，app和app.main。样式都继承了
```
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    <!-- Customize your theme here. -->
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="colorAccent">@color/colorAccent</item>
</style>
```
然后app.main单独运行成功，在host app里面运行失败，报错如下：
```
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mysmall/com.example.mysmall.app.main.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2103)
    at ......
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:340)
    at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
    at com.example.mysmall.app.main.MainActivity.onCreate(MainActivity.java:12)
    at android.app.Activity.performCreate(Activity.java:5013)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:160)
    at ......
```
调试后发现报错代码在AppCompatDelegateImplV7.class
``` 
private ViewGroup createSubDecor() {
    TypedArray a = mContext.obtainStyledAttributes(R.styleable.AppCompatTheme);

    if (!a.hasValue(R.styleable.AppCompatTheme_windowActionBar)) {
        a.recycle();
        throw new IllegalStateException(
                    "You need to use a Theme.AppCompat theme (or descendant) with this activity.");
    }
    ......
}
``` 
此处 TypedArray a = mContext.obtainStyledAttributes(R.styleable.AppCompatTheme);获得的a和app.main单独获得a不同，在hasValue判断时不通过
**这里为什么会出现这个问题？**

又回去看Sample，发现Sample里面的app.main的style是定义在lib.style中，于是原样照做，这时编译报错
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib.style:processReleaseResources'.
> In strict mode, we do not allow vendor aars, please declare them in host build.gradle:
      - compile('com.android.support:appcompat-v7:23.3.0')
  or turn off the strict mode in root build.gradle:
      small {
          strictSplitResources = false
      }

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
按照提示加了small { strictSplitResources = false } 就可以编译通过。strict mode的目的是为了什么？

**Comment by galenlin** [comment]
为了插件最小化，Small默认不允许插件携带第三方资源，包含资源的第三方库必须在宿主里预定义。

后发现`lib.*`插件经常可能这么干，为了灵活性，加开该参数允许用户绕过。

出现AppCompat主题找不到，可能是你用的AppCompat版本与Small自带的冲突了。改成`23.2.1`再重新编译试下。

**Comment by a137235** [comment]
那如果加了这个标识对那些声明过的是否有影响？

**Comment by galenlin** [comment]
@a137235 `声明过的`是什么意思

**Comment by WooYu** [comment]
在宿主中预定义了，还需要在插件中写一次吗

**Comment by whiskeyfei** [comment]
@WayJ 我也出现了 You need to use a Theme.AppCompat theme (or descendant) with this activity 错误，加上 small {
          strictSplitResources = false
      } 这个也不行，还是出错，怎么弄都不好使

**Comment by RonnyWu** [comment]
> You need to use a Theme.AppCompat theme (or descendant) with this activity

you can add compile in the host plugin 'app':

looks so:

````
compile 'com.android.support:appcompat-v7:25.3.1' // A clear version number
````

**Comment by whiskeyfei** [comment]
谢谢，添加上还是不好使，不过已经按照small文档集成demo，已经运行起来，多谢！
