### ISSUE TITLE
在Android N Preview上运行会crash

### ISSUE THREAD

**Issue by cuc-glf** [wequick/Small#154]
看了googleIO，今天给自己的nexus6p更新了N Preview，发现原本能够运行的sample无法运行了，报错如下，无法找到theme属性：
05-19 21:16:10.495 28430-28430/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: main
   Process: net.wequick.example.small, PID: 28430
   java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.example.small.app.main.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2625)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2686)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:5969)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
    Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:340)
       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:50)
       at android.app.Activity.performCreate(Activity.java:6669)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:167)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2578)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2686) 
       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:154) 
       at android.app.ActivityThread.main(ActivityThread.java:5969) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691) 

看出上面的crash是因为没有找到theme属性，修改main中的mainfest，将MainActivity的theme改为AppCompat的theme后，仍然会出其它的错误，报错为无法找到id为0x73xxxxxx的资源。

不知道是N Preview的问题还是Small的问题？

**Comment by galenlin** [comment]
需要等SDK源码出来了再作适配

**Comment by galenlin** [comment]
@cuc-glf 已支持`Android N`，请使用`small:1.1.0-beta3`尝试。
