### ISSUE TITLE
不支持Xposed

### ISSUE THREAD

**Issue by alkaid** [wequick/Small#169]
手机 mx3  flyme os3.7.3 对应android4.2
06-15 11:23:39.348 30145-30145/net.wequick.example.small W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
06-15 11:23:39.348 30145-30145/net.wequick.example.small I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
06-15 11:23:39.348 30145-30145/net.wequick.example.small W/dalvikvm: VFY: unable to resolve interface method 18889: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
06-15 11:23:39.353 30145-30145/net.wequick.example.small D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
06-15 11:23:39.353 30145-30145/net.wequick.example.small I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
06-15 11:23:39.353 30145-30145/net.wequick.example.small W/dalvikvm: VFY: unable to resolve interface method 18893: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
06-15 11:23:39.353 30145-30145/net.wequick.example.small D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
06-15 11:23:39.413 30145-30145/net.wequick.example.small I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
06-15 11:23:39.413 30145-30145/net.wequick.example.small W/dalvikvm: VFY: unable to resolve virtual method 475: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
06-15 11:23:39.413 30145-30145/net.wequick.example.small D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
06-15 11:23:39.413 30145-30145/net.wequick.example.small I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
06-15 11:23:39.413 30145-30145/net.wequick.example.small W/dalvikvm: VFY: unable to resolve virtual method 497: Landroid/content/res/TypedArray;.getType (I)I
06-15 11:23:39.413 30145-30145/net.wequick.example.small D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
06-15 11:23:39.528 30145-30145/net.wequick.example.small D/dalvikvm: GC_FOR_ALLOC freed 297K, 3% free 12752K/13104K, paused 14ms, total 15ms
06-15 11:23:39.663 30145-30160/net.wequick.example.small D/dalvikvm: GC_FOR_ALLOC freed 398K, 4% free 12864K/13320K, paused 14ms, total 14ms
06-15 11:23:39.673 30145-30160/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f09008c
06-15 11:23:39.698 30145-30145/net.wequick.example.small D/OpenGLRenderer: Enabling debug mode 0
06-15 11:23:39.698 30145-30160/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x79030000
06-15 11:23:39.698 30145-30160/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f060014
06-15 11:23:39.703 30145-30160/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f09008c
06-15 11:23:39.733 30145-30160/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f09008c
06-15 11:23:39.748 30145-30160/net.wequick.example.small D/dalvikvm: GC_FOR_ALLOC freed 427K, 4% free 12939K/13424K, paused 17ms, total 17ms
06-15 11:23:39.763 30145-30145/net.wequick.example.small W/ViewRootImpl: mView has no focus, use com.android.internal.policy.impl.PhoneWindow$DecorView{42294ee8 V.E..... R.....ID 0,0-1080,1800} instead
06-15 11:23:39.833 30145-30160/net.wequick.example.small D/dalvikvm: GC_FOR_ALLOC freed 467K, 4% free 12986K/13508K, paused 13ms, total 13ms
06-15 11:23:39.878 30145-30160/net.wequick.example.small W/System.err: java.lang.NoSuchMethodException: <init> [class android.content.res.AssetManager, class android.util.DisplayMetrics, class android.content.res.Configuration]
06-15 11:23:39.883 30145-30160/net.wequick.example.small W/System.err:     at java.lang.Class.getConstructorOrMethod(Class.java:472)
06-15 11:23:39.883 30145-30160/net.wequick.example.small W/System.err:     at java.lang.Class.getConstructor(Class.java:446)
06-15 11:23:39.883 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.util.ReflectAccelerator.newResources(ReflectAccelerator.java:407)
06-15 11:23:39.883 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.ApkBundleLauncher.mergeResources(ApkBundleLauncher.java:625)
06-15 11:23:39.883 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.ApkBundleLauncher.postSetUp(ApkBundleLauncher.java:398)
06-15 11:23:39.883 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.loadBundles(Bundle.java:644)
06-15 11:23:39.883 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.loadBundles(Bundle.java:286)
06-15 11:23:39.883 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.access$100(Bundle.java:63)
06-15 11:23:39.883 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle$LoadBundleThread.run(Bundle.java:629)
06-15 11:23:39.898 30145-30145/net.wequick.example.small D/AndroidRuntime: Shutting down VM
06-15 11:23:39.898 30145-30145/net.wequick.example.small W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4161eba8)
06-15 11:23:39.903 30145-30145/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: net.wequick.example.small, PID: 30145
                                                                           java.lang.NullPointerException
                                                                               at android.app.ContextImpl.getTheme(ContextImpl.java:714)
                                                                               at android.content.ContextWrapper.getTheme(ContextWrapper.java:125)
                                                                               at android.content.Context.obtainStyledAttributes(Context.java:425)
                                                                               at android.view.View.<init>(View.java:3508)
                                                                               at android.view.ViewGroup.<init>(ViewGroup.java:470)
                                                                               at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:52)
                                                                               at android.webkit.WebView.<init>(WebView.java:507)
                                                                               at android.webkit.WebView.<init>(WebView.java:484)
                                                                               at android.webkit.WebView.<init>(WebView.java:464)
                                                                               at android.webkit.WebView.<init>(WebView.java:453)
                                                                               at android.webkit.WebView.<init>(WebView.java:443)
                                                                               at net.wequick.small.webkit.WebView.<init>(WebView.java:124)
                                                                               at net.wequick.small.webkit.WebViewPool.createWebView(WebViewPool.java:177)
                                                                               at net.wequick.small.webkit.WebViewPool.alloc(WebViewPool.java:113)
                                                                               at net.wequick.small.Bundle$LoadBundleHandler.handleMessage(Bundle.java:671)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5032)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                               at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                                                               at dalvik.system.NativeStart.main(Native Method)
06-15 11:23:39.908 30145-30160/net.wequick.example.small D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_64_BIT_ABIS
06-15 11:23:39.908 30145-30160/net.wequick.example.small W/dalvikvm: VFY: unable to resolve static field 115 (SUPPORTED_64_BIT_ABIS) in Landroid/os/Build;
06-15 11:23:39.908 30145-30160/net.wequick.example.small D/dalvikvm: VFY: replacing opcode 0x62 at 0x0061
06-15 11:23:39.908 30145-30160/net.wequick.example.small D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_32_BIT_ABIS
06-15 11:23:39.908 30145-30160/net.wequick.example.small W/dalvikvm: VFY: unable to resolve static field 114 (SUPPORTED_32_BIT_ABIS) in Landroid/os/Build;
06-15 11:23:39.908 30145-30160/net.wequick.example.small D/dalvikvm: VFY: replacing opcode 0x62 at 0x0080
06-15 11:23:39.928 30145-30160/net.wequick.example.small W/System.err: Failed to create file: /data/data/net.wequick.example.small/files/storage/net.wequick.example.small.app.mine/lib/armeabi-v7a/libhello-plugin-jni.so
06-15 11:23:39.933 30145-30160/net.wequick.example.small D/Main Plugin: AppContext()
06-15 11:23:39.933 30145-30160/net.wequick.example.small D/Main Plugin: onCreate()
06-15 11:23:39.933 30145-30160/net.wequick.example.small D/Main Plugin: {net.wequick.example.small.app.detail=1, net.wequick.example.small.app.mine=1, net.wequick.example.small.app.home=1, net.wequick.example.small.lib.utils=1, net.wequick.example.small.web.about=1, com.example.mysmall.lib.style=1, net.wequick.example.small.app.main=1}
06-15 11:23:39.933 30145-30160/net.wequick.example.small W/System.err: java.lang.NullPointerException
06-15 11:23:39.933 30145-30160/net.wequick.example.small W/System.err:     at android.content.Context.getString(Context.java:343)
06-15 11:23:39.933 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.example.small.app.main.AppContext.onCreate(AppContext.java:26)
06-15 11:23:39.933 30145-30160/net.wequick.example.small W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
06-15 11:23:39.933 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.ApkBundleLauncher.postSetUp(ApkBundleLauncher.java:455)
06-15 11:23:39.933 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.loadBundles(Bundle.java:644)
06-15 11:23:39.933 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.loadBundles(Bundle.java:286)
06-15 11:23:39.933 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.access$100(Bundle.java:63)
06-15 11:23:39.933 30145-30160/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle$LoadBundleThread.run(Bundle.java:629)

**Comment by galenlin** [comment]
你好，看上去是你的设备修改了底层代码，导致了不兼容。
```
System.err: java.lang.NoSuchMethodException: [class android.content.res.AssetManager, class android.util.DisplayMetrics, class android.content.res.Configuration]
System.err: at java.lang.Class.getConstructorOrMethod(Class.java:472)
System.err: at java.lang.Class.getConstructor(Class.java:446)
System.err: at net.wequick.small.util.ReflectAccelerator.newResources(ReflectAccelerator.java:407)
```

可否协助调试下：
在`ReflectAccelerator.java`的`newResources`函数，看下`resourcesClass`以及`resourcesClass.getConstructors()`的值。

**Comment by alkaid** [comment]
![image](https://cloud.githubusercontent.com/assets/1241940/16069220/51902bd8-32ff-11e6-9938-102e9952653f.png)
constructor拿不到  。。。擦 是不是因为xposed

**Comment by alkaid** [comment]
额 XResources就是xposed的 换了个设备OK了

**Comment by galenlin** [comment]
哦。方便的话看能否协助兼容下，提个PR

**Comment by alkaid** [comment]
还在跑demo的阶段  找时间弄弄看哈。。。
BTW 现在新增一个插件放在server下载到本地后能不能马上加载呢？还是一定要重启的？

**Comment by galenlin** [comment]
目前需要重启

**Comment by galenlin** [comment]
新版本已解决，请使用`small:1.1.0-beta4`尝试
