### ISSUE TITLE
 运行Ｓａｍｐｌｅ出现ＦＣ问题

### ISSUE THREAD

**Issue by zhouzhengting** [wequick/Small#176]
06-24 09:43:36.174 10901-10901/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: net.wequick.example.small, PID: 10901
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.example.small.app.main.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2546)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2612)
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1468)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                               at android.os.Looper.loop(Looper.java:207)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5729)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
                                                                            Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:340)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
                                                                               at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:50)
                                                                               at android.app.Activity.performCreate(Activity.java:6270)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                               at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:167)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2499)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2612) 
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1468) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                               at android.os.Looper.loop(Looper.java:207) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5729) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by galenlin** [comment]
看下是否是appcompat包版本不一致导致的

**Comment by zhouzhengting** [comment]
只能是Sample build.gradle配置的版本：com.android.support:appcompat-v7:23.2.1'　吗？
