### ISSUE TITLE
第三库里的资源找不到，然后闪退！

### ISSUE THREAD

**Issue by halibobo** [wequick/Small#194]
第三库里的资源找不到，然后闪退！
比如阿里的
`java.lang.NoClassDefFoundError: com.alibaba.sdk.android.R$layout
                                                                             at com.alibaba.sdk.android.feedback.windvane.WXBaseHybridActivity.setErrorView(WXBaseHybridActivity.java:135)
                                                                             at com.alibaba.sdk.android.feedback.windvane.WXBaseHybridActivity.onCreate(WXBaseHybridActivity.java:78)
                                                                             at com.alibaba.sdk.android.feedback.windvane.CustomHybirdActivity.onCreate(CustomHybirdActivity.java:85)
                                                                             at android.app.Activity.performCreate(Activity.java:5143)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)`

**Comment by zirconnnn** [comment]
这个我也碰到了。app类型的插件引用一个正常的library module，如果这个library module了引用了R相关的资源，就会报这个错。

**Comment by galenlin** [comment]
感谢反馈，近期处理

**Comment by galenlin** [comment]
@halibobo 你使用的gradle-small版本多少

**Comment by kongyan4696** [comment]
类似问题归类 #171

**Comment by zirconnnn** [comment]
@galenlin 我用的是最新版0.9

**Comment by halibobo** [comment]
@galenlin 
 'net.wequick.tools.build:gradle-small:0.9.0'
small {
    aarVersion = '1.0.0'
}

**Comment by galenlin** [comment]
@halibobo @zirconnnn DevSample已经更新了，烦请pull尝试下是否解决问题

**Comment by zirconnnn** [comment]
貌似还不行。R文件还是没生成。

**Comment by galenlin** [comment]
@zirconnnn 用DevSample的buildSrc编译的吗？

**Comment by zirconnnn** [comment]
@galenlin 是的。我是把buildSrc直接拷贝到Sample根目录下，然后apply 这个plugin就可以了吧。

**Comment by galenlin** [comment]
@zirconnnn 可否提供下demo，我调试下看看

**Comment by zirconnnn** [comment]
@galenlin 只要在Sample工程下新建个library module比如叫mylibrary，mylibrary里有一个自定义的textview，然后引用了一个R.string.xxx，lib.detail模块引入这个mylibrary并调用这个自定义textview ，就会报R$String NoClassDefFoundError，看了下R文件没有生成。

**Comment by galenlin** [comment]
@zirconnnn 这个我在DevSample试过可以了，已经生成相应的R类

**Comment by galenlin** [comment]
@zirconnnn 你已经更新DevSample了吗？

**Comment by zirconnnn** [comment]
@galenlin 我的Sample在这里 ，望调试下看看。http://yun.baidu.com/share/link?shareid=1512559957&uk=50381242

**Comment by offbye** [comment]
升级到1.0.0beta3 这个bug用出现了
