### ISSUE TITLE
启动插件时报错，必现！（插件app比较大）

### ISSUE THREAD

**Issue by halibobo** [wequick/Small#208]
报错信息如下： 
`FATAL EXCEPTION: Thread-507
                                                                     java.lang.IllegalArgumentException: expected receiver of type android.app.ContextImpl, but got com.apple.adminapp.HostApp
                                                                         at java.lang.reflect.Field.setField(Native Method)
                                                                         at java.lang.reflect.Field.set(Field.java:588)
                                                                         at net.wequick.small.util.ReflectAccelerator.setValue(ReflectAccelerator.java:593)
                                                                         at net.wequick.small.util.ReflectAccelerator.setResources(ReflectAccelerator.java:471)
                                                                         at net.wequick.small.util.ReflectAccelerator.setResources(ReflectAccelerator.java:454)
                                                                         at net.wequick.small.ApkBundleLauncher.postSetUp(ApkBundleLauncher.java:400)
                                                                         at net.wequick.small.Bundle.loadBundles(Bundle.java:673)
                                                                         at net.wequick.small.Bundle.loadBundles(Bundle.java:287)
                                                                         at net.wequick.small.Bundle.access$100(Bundle.java:64)
                                                                         at net.wequick.small.Bundle$LoadBundleThread.run(Bundle.java:638)`

**Comment by galenlin** [comment]
@halibobo 调试下看看，`ReflectAccelerator.java`:454行，`app`以及`app.getBaseContext()`各是什么。

**Comment by galenlin** [comment]
@halibobo `small:1.1.0-beta3`已使用新方法整合插件资源，请尝试。
