### ISSUE TITLE
Android N报错No field mActiveResources in class Landroid/app/ResourcesManager

### ISSUE THREAD

**Issue by offbye** [wequick/Small#223]
Devsample在Nexus 6手机Android N系统下报错No field mActiveResources in class Landroid/app/ResourcesManager ，但我已经查过Android源码，发现源码有这个字段mActiveResources
源码地址 
https://android.googlesource.com/platform/frameworks/base/+/android-n-preview-2/core/java/android/app/ResourcesManager.java
```java
/** @hide */
public class ResourcesManager {
    static final String TAG = "ResourcesManager";
    private static final boolean DEBUG = false;
    private static ResourcesManager sResourcesManager;
    private final ArrayMap<ResourcesKey, WeakReference<Resources> > mActiveResources =
            new ArrayMap<>();
    private final ArrayMap<Pair<Integer, DisplayAdjustments>, WeakReference<Display>> mDisplays =
            new ArrayMap<>();
    CompatibilityInfo mResCompatibilityInfo;
    Configuration mResConfiguration;
    public static ResourcesManager getInstance() {
        synchronized (ResourcesManager.class) {
            if (sResourcesManager == null) {
                sResourcesManager = new ResourcesManager();
            }
            return sResourcesManager;
        }
    }

```

```
07-19 16:49:45.419 30665-30685/net.wequick.example.small I/Adreno: QUALCOMM build                   : ab9e4b3, I3ad86ef6a3
                                                                   Build Date                       : 05/19/16
                                                                   OpenGL ES Shader Compiler Version: XE031.08.00.02
                                                                   Local Branch                     : 
                                                                   Remote Branch                    : 
                                                                   Remote Branch                    : 
                                                                   Reconstruct Branch               : 
07-19 16:49:45.517 30665-30685/net.wequick.example.small I/OpenGLRenderer: Initialized EGL, version 1.4
07-19 16:49:45.517 30665-30685/net.wequick.example.small D/OpenGLRenderer: Swap behavior 1
07-19 16:49:45.653 30665-30684/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f0900f2
07-19 16:49:45.679 30665-30684/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f0900ff
07-19 16:49:45.679 30665-30684/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f060014
07-19 16:49:45.707 30665-30684/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f09008c
07-19 16:49:45.777 30665-30684/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x7f09008c
07-19 16:49:46.668 30665-30684/net.wequick.example.small W/System.err: java.lang.NoSuchFieldException: No field mActiveResources in class Landroid/app/ResourcesManager; (declaration of 'android.app.ResourcesManager' appears in /system/framework/framework.jar)
07-19 16:49:46.668 30665-30684/net.wequick.example.small W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
07-19 16:49:46.668 30665-30684/net.wequick.example.small W/System.err:     at net.wequick.small.util.ReflectAccelerator$V19_.updateTopLevelResources(ReflectAccelerator.java:264)
07-19 16:49:46.668 30665-30684/net.wequick.example.small W/System.err:     at net.wequick.small.util.ReflectAccelerator.setResources(ReflectAccelerator.java:461)
07-19 16:49:46.668 30665-30684/net.wequick.example.small W/System.err:     at net.wequick.small.ApkBundleLauncher.postSetUp(ApkBundleLauncher.java:400)
07-19 16:49:46.668 30665-30684/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.loadBundles(Bundle.java:704)
07-19 16:49:46.669 30665-30684/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.loadBundles(Bundle.java:305)
07-19 16:49:46.669 30665-30684/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle.access$100(Bundle.java:64)
07-19 16:49:46.669 30665-30684/net.wequick.example.small W/System.err:     at net.wequick.small.Bundle$LoadBundleThread.run(Bundle.java:668)
07-19 16:49:46.672 30665-30684/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-19 16:49:46.672 30665-30684/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-19 16:49:46.672 30665-30684/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-19 16:49:46.672 30665-30684/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-19 16:49:46.672 30665-30684/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-19 16:49:46.672 30665-30684/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-19 16:49:46.672 30665-30684/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-19 16:49:46.673 30665-30684/net.wequick.example.small W/art: The dalvik.system.DexPathList$Element constructor is not accessible by default. This is a temporary workaround for backwards compatibility with class-loader hacks. Please update your application.
07-19 16:49:46.675 30665-30665/net.wequick.example.small D/Main Plugin: AppContext()
07-19 16:49:46.675 30665-30665/net.wequick.example.small D/Main Plugin: onCreate()
07-19 16:49:46.676 30665-30665/net.wequick.example.small D/Main Plugin: {net.wequick.example.small.app.detail=1, net.wequick.example.small.web.about=1, com.example.mysmall.lib.style=1, net.wequick.example.small.app.mine=1, net.wequick.example.small.app.home=1, net.wequick.example.small.lib.utils=1, net.wequick.example.lib.analytics=1, net.wequick.example.small.app.main=1}
07-19 16:49:46.676 30665-30665/net.wequick.example.small D/Main Plugin: Settings
07-19 16:49:46.712 30665-30665/net.wequick.example.small I/System.out: onActivityPaused net.wequick.example.small.LaunchActivity
07-19 16:49:46.747 30665-30665/net.wequick.example.small I/System.out: ## Small setUp in 1396.08 ms.
07-19 16:49:46.752 30665-30665/net.wequick.example.small I/System.out: ## Small start first activity in 75.18032 ms.
07-19 16:49:46.786 30665-30665/net.wequick.example.small W/ResourceType: No known package when getting value for resource number 0x77020000
07-19 16:49:46.788 30665-30665/net.wequick.example.small D/AndroidRuntime: Shutting down VM
07-19 16:49:46.970 30665-30665/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: net.wequick.example.small, PID: 30665
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.example.small.app.main.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x77020000
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2692)
                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6044)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                            Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x77020000
                                                                               at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:182)
                                                                               at android.content.res.Resources.loadXmlResourceParser(Resources.java:2089)
                                                                               at android.content.res.Resources.getLayout(Resources.java:1111)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                               at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71)
                                                                               at android.app.Activity.performCreate(Activity.java:6658)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                               at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:168)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2584)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2692) 
                                                                               at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6044) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
07-19 16:50:09.139 30665-30672/net.wequick.example.small W/art: Suspending all threads took: 5.050ms
```

**Comment by galenlin** [comment]
@offbye 试下[replace-assets](https://github.com/wequick/Small/tree/replace-assets)看看

**Comment by galenlin** [comment]
@offbye master已合并该分支。测试已支持Android N。
