### ISSUE TITLE
Binary XML file line #26: Error inflating class android.support.design.widget.TabLayout

### ISSUE THREAD

**Issue by linmp4** [wequick/Small#229]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: net.wequick.example.small, PID: 26689
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.example.small.app.main.MainActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.TabLayout
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
                      at android.app.ActivityThread.access$800(ActivityThread.java:169)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                      at android.os.Handler.dispatchMessage(Handler.java:111)
                      at android.os.Looper.loop(Looper.java:194)
                      at android.app.ActivityThread.main(ActivityThread.java:5546)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                   Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.TabLayout
                      at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71)
                      at android.app.Activity.performCreate(Activity.java:5975)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                      at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:168)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:194) 
                      at android.app.ActivityThread.main(ActivityThread.java:5546) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:611)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                      at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
                      at android.app.Activity.performCreate(Activity.java:5975) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                      at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:168) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:194) 
                      at android.app.ActivityThread.main(ActivityThread.java:5546) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
                   Caused by: android.content.res.Resources$NotFoundException: Resource "net.wequick.example.small:id/useLogo" (7f0c0014)  is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=6 r=0x7f0c0014}
                      at android.content.res.Resources.loadDrawableForCookie(Resources.java:2687)
                      at android.content.res.Resources.loadDrawable(Resources.java:2607)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:751)
                      at android.view.View.<init>(View.java:3777)
                      at android.view.ViewGroup.<init>(ViewGroup.java:518)
                      at android.widget.FrameLayout.<init>(FrameLayout.java:133)
                      at android.widget.HorizontalScrollView.<init>(HorizontalScrollView.java:155)
                      at android.widget.HorizontalScrollView.<init>(HorizontalScrollView.java:150)
                      at android.support.design.widget.TabLayout.<init>(TabLayout.java:265)
                      at android.support.design.widget.TabLayout.<init>(TabLayout.java:261)
                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                      at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
                      at android.app.Activity.performCreate(Activity.java:5975) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                      at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:168) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:194) 
                      at android.app.ActivityThread.main(ActivityThread.java:5546) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by sailor1861** [comment]
I have the same error; how to solve?

**Comment by sailor1861** [comment]
能否帮助下，无法运行

**Comment by galenlin** [comment]
gradle-small的版本是否是1.0.0-beta3?

**Comment by garseen** [comment]
我也是出现这种报错 用的是1.0.0-beta3,请教下怎么解决啊

**Comment by galenlin** [comment]
@linmp4 从你的log看到关键的错误是：
```
Caused by: android.content.res.Resources$NotFoundException: Resource "net.wequick.example.small:id/useLogo" (7f0c0014) is not a Drawable
```
这个`useLogo`是来自于哪里的呢？
另外，请检查下design包的版本在插件跟宿主中是否一致。

**Comment by fengnudexiaoniao** [comment]
遇到类似问题，感觉最终是这句引起的  Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
求大神解答，出错场景，再app中引入了自己项目的aar包，就会出现这个问题

相信错误信息：
        Process: net.wequick.example.small, PID: 4221
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.example.small.app.main.MainActivity}: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class android.support.design.widget.AppBarLayout
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class android.support.design.widget.AppBarLayout
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                     at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71)
                                                     at android.app.Activity.performCreate(Activity.java:6237)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                  Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class android.support.design.widget.AppBarLayout
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                     at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
                                                     at android.app.Activity.performCreate(Activity.java:6237) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                     at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                     at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
                                                     at android.app.Activity.performCreate(Activity.java:6237) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                     at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                  Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
                                                     at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:666)
                                                     at android.view.View.<init>(View.java:3963)
                                                     at android.view.ViewGroup.<init>(ViewGroup.java:573)
                                                     at android.widget.LinearLayout.<init>(LinearLayout.java:203)
                                                     at android.widget.LinearLayout.<init>(LinearLayout.java:199)
                                                     at android.widget.LinearLayout.<init>(LinearLayout.java:195)
                                                     at android.support.design.widget.AppBarLayout.<init>(AppBarLayout.java:142)
                                                     at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                     at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
                                                     at android.app.Activity.performCreate(Activity.java:6237) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                     at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by chenlong0530** [comment]
遇到同样的问题，求助。。。
