### ISSUE TITLE
360卫士极客版会拦截startActivity，导致Small启动失败

### ISSUE THREAD

**Issue by icodeu** [wequick/Small#245]
装了360卫士极客版(V2.1.9.1008 全新安装，未做其它设置)，点开App报如下异常；卸载掉该安全卫士，Small正常运行
/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: net.wequick.example.small, PID: 15327
                                                                           android.content.ActivityNotFoundException: Unable to find explicit activity class {net.wequick.example.small/net.wequick.example.small.app.detail.MainActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                               at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1766)
                                                                               at android.app.Instrumentation.execStartActivity(Instrumentation.java:1491)
                                                                               at **com.qihoo360.mobilesafe.loader.c.execStartActivity**(SourceFile:414)
                                                                               at android.app.Activity.startActivityForResult(Activity.java:3780)
                                                                               at android.app.Activity.startActivityForResult(Activity.java:3741)
                                                                               at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:843)
                                                                               at net.wequick.small.BundleLauncher.launchBundle(BundleLauncher.java:169)
                                                                               at net.wequick.small.ApkBundleLauncher.launchBundle(ApkBundleLauncher.java:624)
                                                                               at net.wequick.small.Bundle.launchFrom(Bundle.java:521)
                                                                               at net.wequick.small.Small.openUri(Small.java:268)
                                                                               at net.wequick.small.Small.openUri(Small.java:250)
                                                                               at net.wequick.example.small.app.home.MainFragment$1.onClick(MainFragment.java:45)
                                                                               at android.view.View.performClick(View.java:4815)
                                                                               at android.view.View$PerformClick.run(View.java:19875)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5277)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)

**Comment by galenlin** [comment]
@icodeu 我试了下，似乎没发现这个问题额。

**Comment by galenlin** [comment]
@icodeu 已经复现了问题，稍后提交代码兼容
