### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by caijingfile** [wequick/Small#249]
Caused by: java.lang.IllegalStateException: [You need to use a Theme.AppCompat theme (or descendant) with this activity.]([url](url))
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:340)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                               at net.wequick.example.small.app.detail.MainActivity.onCreate(MainActivity.java:20)
                                                                               at android.app.Activity.performCreate(Activity.java:6251)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                               at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

修改了app.detail模块activity_main.xml里面的内容后。通过app上 Check Upgrade按钮更新后；直接去点击Open app.detail按钮闪退了。报上面这个异常。闪退后下次再点击Open app.detail按钮就不会出现这个异常。我看app.detail里面的Activity是继承的AppCompatActivity，Style上也是继承的Theme.AppCompat.Light.DarkActionBar；按理说不应该缺少Theme.AppCompat theme吧！为什么动态更新就会出现这问题了？

**Comment by mygift2016** [comment]
应该是V7或者V4包重复引用的问题

**Comment by caijingfile** [comment]
我是直接down了Small源码实验的。在app.detail和lib.style确实都引用了V7包。我删掉了app.detail下的V7包。但我热更新app.detail里的布局文件后，界面数据有时候变了有时候又不变，变的时候必需退到后台，才能去点击Open app.detail按钮。如果直接点击Open app.detail按钮就会跟前面说的一样，会报那个异常。哎。。。算了   不纠结这个了   我还是去看看其他的热更新的项目

**Comment by offbye** [comment]
只引用v7包，v7已经引用了v4

**Comment by kco0910** [comment]
我使用的是Sample的项目，app.detail 的MainActivity是使用的自定义主题MyAppTheme，进入界面后点击
Open app.detail，报楼主说的错误，我只有将MyAppTheme改为AppTheme才能正常使用。但是MyAppTheme就是AppTheme的子样式。

还有一个问题，一旦异常退出，App都不能重新启动，这个很致命。

**Comment by galenlin** [comment]
@caijingfile @kco0910 感谢反馈，问题原因已找到：

> 当“插件A继承插件B的主题”时会导致该错误

本质在于wiki里提到的DynamicRefTable，由于目前插件A编译时只添加了自身的DynamicRefTable，所以当递归查找主题的`parent`时，无法追溯到插件B，即AppCompat相关主题，从而引发Crash。

现该问题已解决，发布在`gradle-small:1.0.0-beta6`

**Comment by kco0910** [comment]
tks

**Comment by zhaojian1989322** [comment]
同样遇到了该问题，不知道最后大家怎么解决的？我用的是beta8，说beta6解决了的麻烦描述下具体该怎么解决？

**Comment by galenlin** [comment]
@zhaojian1989322 能否将demo发我看下。

**Comment by gordonpro** [comment]
beta9 偶尔也有

**Comment by parcool** [comment]
我这beta9 一定有。

**Comment by JtangXian** [comment]
开始碰到同样的问题，后面将small {
    aarVersion = '1.1.0-beta6'
    strictSplitResources = false
} 
改成small {
    aarVersion = '1.1.0-beta6'
    strictSplitResources = false
    android {
        compileSdkVersion = 23
        buildToolsVersion = "23.0.3"
        supportVersion = "23.4.0"
    }
} 就好了

**Comment by aheadlcx** [comment]
@galenlin 1.1.0-alpha1 一样出现该问题，导入 DevSample 就可以重现了。
