### ISSUE TITLE
自定义的组件必须放在lib.*工程里吗？

### ISSUE THREAD

**Issue by eity0323** [wequick/Small#251]
app.*下的自定义组件在xml中引用报错

` java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/com.suneee.circle.app.circle.activity.TestActivity}: android.view.InflateException: Binary XML file line #14: Error inflating class com.suneee.circle.app.circle.widgets.MaskedImage
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                            Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.suneee.circle.app.circle.widgets.MaskedImage
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                               at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378)
                                                                               at android.app.Activity.setContentView(Activity.java:2145)
                                                                               at com.suneee.circle.app.circle.activity.TestActivity.onCreate(TestActivity.java:21)
                                                                               at android.app.Activity.performCreate(Activity.java:5990)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)`

**Comment by eity0323** [comment]
#207 在这个issue中找到说明了：基本原则
lib.utils - 公共API、公共控件
