### ISSUE TITLE
使用TextView时，添加了android:text="@string/welcome"  或android:background="@drawable/bg_progress_bar_black" 就会报下面的错误，删除不用就好了。

### ISSUE THREAD

**Issue by clxxcl** [wequick/Small#254]
08-06 16:25:13.001 1895-1895/com.raymi.mifm E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.raymi.mifm, PID: 1895
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.raymi.mifm/com.raymi.mifm.app.main.LoginActivity}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class <unknown>
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                               Caused by: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class <unknown>
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
                                                                  at android.app.Activity.setContentView(Activity.java:2183)
                                                                  at com.raymi.mifm.app.main.LoginActivity.onCreate(LoginActivity.java:58)
                                                                  at android.app.Activity.performCreate(Activity.java:6303)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                  at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                               Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class <unknown>
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:649)
                                                                  at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                                                  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                  at android.app.Activity.setContentView(Activity.java:2183) 
                                                                  at com.raymi.mifm.app.main.LoginActivity.onCreate(LoginActivity.java:58) 
                                                                  at android.app.Activity.performCreate(Activity.java:6303) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                  at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                  at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                  at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                  at android.app.Activity.setContentView(Activity.java:2183) 
                                                                  at com.raymi.mifm.app.main.LoginActivity.onCreate(LoginActivity.java:58) 
                                                                  at android.app.Activity.performCreate(Activity.java:6303) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                  at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                               Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=6
                                                                  at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:276)
                                                                  at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1158)
                                                                  at android.content.res.TypedArray.getText(TypedArray.java:160)
                                                                  at android.content.res.MiuiTypedArray.getText(MiuiTypedArray.java:23)
                                                                  at android.widget.TextView.<init>(TextView.java:976)
                                                                  at android.widget.TextView.<init>(TextView.java:674)
                                                                  at android.widget.TextView.<init>(TextView.java:670)
                                                                  at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
                                                                  at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
                                                                  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766) 
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:842) 
                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                  at android.app.Activity.setContentView(Activity.java:2183) 
                                                                  at com.raymi.mifm.app.main.LoginActivity.onCreate(LoginActivity.java:58) 
                                                                  at android.app.Activity.performCreate(Activity.java:6303) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                  at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by clxxcl** [comment]
最新版1.0.0-beta5好了

**Comment by chenlong0530** [comment]
为什么1.0.0-beta5我下载不下来？
