### ISSUE TITLE
hello, 跳去插件界面findViewById后,TextView为null，初始化不了

### ISSUE THREAD

**Issue by DHGHH** [wequick/Small#255]
public class MineActivity extends AppCompatActivity {

    private TextView tv_login;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_mine);
        tv_login=(TextView)findViewById(R.id.tv_login);
        if (tv_login==null){
            Toast.makeText(this,"tv_login is null", Toast.LENGTH_SHORT).show();
        }
        else {
            Toast.makeText(this,"tv_login is ok", Toast.LENGTH_SHORT).show();
        }

      /*  tv_login.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Small.openUri("login",MineActivity.this);
            }
        });*/
    }

}

**Comment by DHGHH** [comment]
用了最新的版本beta-5还是不可以

 Process: com.bbk.app.main, PID: 24411
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bbk.app.main/com.bbk.hh.app.mine.MineActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:731)
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                      at com.bbk.hh.app.mine.MineActivity.onCreate(MineActivity.java:29)
                                                                      at android.app.Activity.performCreate(Activity.java:5933)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)

**Comment by galenlin** [comment]
使用beta5重新编译了吗？
检查方法：
1. `aapt list libcom_bbk_hh_app_mine.so` 看是否有重复的`res/layout/activity_mine.xml`
2. `aapt d --values xmltree libcom_bbk_hh_app_mine.so res/layout/activity_mine.xml` 看其中的`tv_login`值是否与`在代码中打印出来`的相同。

**Comment by DHGHH** [comment]
你刚才是不是更新了? 现在可以了，谢谢

**Comment by galenlin** [comment]
好的，beta5是前些天已经发布了的。感谢反馈，关闭本问题。
