### ISSUE TITLE
碰到一个问题：插件中添加权限无效，要发到宿主中才行。可给的demo中就是放在插件中的。

### ISSUE THREAD

**Issue by clxxcl** [wequick/Small#257]
java.lang.SecurityException: ConnectivityService: Neither user 10874 nor current process has android.permission.ACCESS_NETWORK_STATE.
                                                                    at android.os.Parcel.readException(Parcel.java:1620)
                                                                    at android.os.Parcel.readException(Parcel.java:1573)
                                                                    at android.net.IConnectivityManager$Stub$Proxy.getNetworkInfo(IConnectivityManager.java:1075)
                                                                    at android.net.ConnectivityManager.getNetworkInfo(ConnectivityManager.java:732)
                                                                    at com.raymi.mifm.lib.util.NetUtils.isWIFIConnected(NetUtils.java:30)
                                                                    at com.raymi.mifm.lib.util.NetUtils.checkNet(NetUtils.java:20)
                                                                    at com.raymi.mifm.app.login.LoginActivity.onClick(LoginActivity.java:92)
                                                                    at android.view.View.performClick(View.java:5207)
                                                                    at android.view.View$PerformClick.run(View.java:21177)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by galenlin** [comment]
权限肯定是要在宿主注册的。
你看到的demo里的某些权限其实是在_**编译时期**_从`small aar`合并到宿主的。
你可以看看`app/build/intermediates/manifests/`下的`AndroidManifest.xml`就明白了。
