### ISSUE TITLE
android 6.0.1 启动插件activity出现android.content.pm.PackageManager$NameNotFoundException

### ISSUE THREAD

**Issue by tcking** [wequick/Small#261]
**前提**
android 6.0.1

**现象**
activity启动时出现如下日志，但是app并没有crash掉
```
W/ResourcesManager: getTopLevelResources: /data/app/com.test-1/base.apk / 1.0 running in com.test rsrc of package com.test
08-09 16:04:01.157 4634-4634/com.test W/System.err: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.test/com.test.app.main.activity.MainActivity}
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:404)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4831)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2263)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.view.Window.findViewById(Window.java:1049)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:469)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at com.test.app.main.activity.MainActivity.onCreate(MainActivity.java:99)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.app.Activity.performCreate(Activity.java:6876)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:170)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:222)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.os.Looper.loop(Looper.java:158)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7237)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
08-09 16:04:01.157 4634-4634/com.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:112
```

在6+里貌似还要hack packageManager

**Comment by galenlin** [comment]
我用Sample在模拟器下跑好像没看到这个错误，是不是跟v7版本有关？

**Comment by tcking** [comment]
v7用的是23.4.0

**Comment by tcking** [comment]
从日志看应该还是android sdk的，在installDecor时会去调pm的getActivityInfo，此时找不到插件中的activityInfo

**Comment by WooYu** [comment]
今天我也碰到这个问题了，@tcking 你解决了没

**Comment by 601367322** [comment]
遇到了同样的问题！！！

**Comment by YujieShui** [comment]
所以怎么解决的？

**Comment by joleyii** [comment]
有办法解决喵
