### ISSUE TITLE
第三方库引用来自AppCompat的colorAccent找不到

### ISSUE THREAD

**Issue by mygift2016** [wequick/Small#271]
引用 compile 'com.afollestad.material-dialogs:core:0.8.6.2'
来自AppCompat的colorAccent找不到

报错信息如下：
08-15 15:49:50.281 6967-6967/com.sunfusheng.small E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.sunfusheng.small, PID: 6967
                                                                    java.lang.NoSuchFieldError: com.afollestad.materialdialogs.R$attr.colorAccent
                                                                        at com.afollestad.materialdialogs.MaterialDialog$Builder.<init>(MaterialDialog.java:494)
                                                                        at com.sunfusheng.small.lib.framework.proxy.handler.BaseHandler.<init>(BaseHandler.java:22)
                                                                        at com.sunfusheng.small.lib.framework.proxy.handler.AsyncActivityHandler.<init>(AsyncActivityHandler.java:9)
                                                                        at com.sunfusheng.small.lib.framework.proxy.helper.ActivityHelper.<init>(ActivityHelper.java:14)
                                                                        at com.sunfusheng.small.lib.framework.base.BaseAsyncActivity.onCreate(BaseAsyncActivity.java:26)
                                                                        at com.sunfusheng.small.lib.framework.base.BaseActivity.onCreate(BaseActivity.java:26)
                                                                        at com.sunfusheng.small.app.main.MainActivity.onCreate(MainActivity.java:46)
                                                                        at android.app.Activity.performCreate(Activity.java:5311)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                        at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:167)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2283)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2370)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1243)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5426)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by galenlin** [comment]
gradle-small以及small版本多少？

**Comment by mygift2016** [comment]
beta7版本

应该是attrs文件资源分配引起的吧？

**Comment by galenlin** [comment]
补充说明下，这个问题是由于第三方aar在代码中引用了外部的一些aar中的资源。比如AppCompat的`R.attr.colorAccent`。

在原算法中对第三方aar的`R.java`做了特殊处理，只保留自己定义的资源，这样能够使插件最小化。

为解决这个问题，同时保证插件最小化，现对aar的`classes.jar`中的class文件进行解析，收集所有引用到的`R.*.*`字段，并保留到上述`R.java`中。

相关的代码改动见 1bdd0d2
