### ISSUE TITLE
Caused by: groovy.lang.MissingFieldException: No such field: name for class: java.lang.String

### ISSUE THREAD

**Issue by 729286938** [wequick/Small#286]
完整错误日志如下：
暂不清楚是什么原因导致
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':lib.style:processReleaseResources'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: groovy.lang.MissingFieldException: No such field: name for class: java.lang.String
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53$_closure87$_closure88$_closure89$_closure90.doCall(AppPlugin.groovy:1216)
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53$_closure87$_closure88$_closure89.doCall(AppPlugin.groovy:1215)
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53$_closure87$_closure88.doCall(AppPlugin.groovy:1206)
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53$_closure87.doCall(AppPlugin.groovy:1196)
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53.doCall(AppPlugin.groovy:1193)
        at net.wequick.gradle.AppPlugin.collectReservedResourceKeys(AppPlugin.groovy:1192)
        at net.wequick.gradle.AppPlugin.getReservedResourceKeys(AppPlugin.groovy:1173)
        at net.wequick.gradle.AppPlugin.prepareSplit(AppPlugin.groovy:457)
        at net.wequick.gradle.AppPlugin$_hookAapt_closure46.doCall(AppPlugin.groovy:1029)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more

**Comment by galenlin** [comment]
能否在Sample复现，或提供你的demo给我调试下。

**Comment by FreeTotoro** [comment]
我也遇到了。。。把一个之前以普通library依赖的module，转成small可识别的lib依赖库之后，build就报这个错了。。

**Comment by FreeTotoro** [comment]
Caused by: groovy.lang.MissingFieldException: No such field: name for class: java.lang.String
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53$_closure87$_closure88$_closure89$_closure90.doCall(AppPlugin.groovy:1216)
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53$_closure87$_closure88$_closure89.doCall(AppPlugin.groovy:1215)
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53$_closure87$_closure88.doCall(AppPlugin.groovy:1206)
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53$_closure87.doCall(AppPlugin.groovy:1196)
        at net.wequick.gradle.AppPlugin$_collectReservedResourceKeys_closure53.doCall(AppPlugin.groovy:1193)
        at net.wequick.gradle.AppPlugin.collectReservedResourceKeys(AppPlugin.groovy:1192)
        at net.wequick.gradle.AppPlugin.getReservedResourceKeys(AppPlugin.groovy:1173)
        at net.wequick.gradle.AppPlugin.prepareSplit(AppPlugin.groovy:457)
        at net.wequick.gradle.AppPlugin$_hookAapt_closure46.doCall(AppPlugin.groovy:1029)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more

**Comment by gordonpro** [comment]
@FreeTotoro 你解决了吗？ 我也遇到了

**Comment by gordonpro** [comment]
我先遇到了一个要加 ext.packageId=0x7e 的issue. packageId 重复。
然后照着文档添加之后， 就遇到了这个问题

**Comment by LionelWei** [comment]
遇到了同样的问题, 原因是<declare-styleable>中有多余字符, 导致解析失败 (如下所示, 多了一个"-") 坑爹的是gradle编译是正常的!
```
    <!--  style for auto ratio ImageView -->
    <declare-styleable name="AutoRatioImageView">
        - <!--  多了左边这个字符  -->
        <attr name="ratio" format="float" />
        <attr name="prefer" format="integer" />
    </declare-styleable>
```
