### ISSUE TITLE
android.view.InflateException: Binary XML file line #25: Error inflating class android.support.v7.widget.ViewStubCompat

### ISSUE THREAD

**Issue by pessonljxpd** [wequick/Small#292]
08-25 09:51:40.027 21760-21760/com.xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.xxx.xxx , PID: 21760
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx /com.xxx.xxx .app.xxx.activity.SplashActivity}: android.view.InflateException: Binary XML file line #25: Error inflating class android.support.v7.widget.ViewStubCompat
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                         Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class android.support.v7.widget.ViewStubCompat
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:413)
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264)
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:141)
                                                                            at com.ses.maintainassist.app.wind.BaseAppCompatActivity.onCreate(BaseAppCompatActivity.java:60)
                                                                            at android.app.Activity.performCreate(Activity.java:5264)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                            at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:168)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                            at android.os.Looper.loop(Looper.java:193) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:413) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:141) 
                                                                            at com.ses.maintainassist.app.wind.BaseAppCompatActivity.onCreate(BaseAppCompatActivity.java:60) 
                                                                            at android.app.Activity.performCreate(Activity.java:5264) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                            at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:168) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                            at android.os.Looper.loop(Looper.java:193) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                                            at android.support.v7.widget.ViewStubCompat.<init>(ViewStubCompat.java:53)
                                                                            at android.support.v7.widget.ViewStubCompat.<init>(ViewStubCompat.java:47)
                                                                            at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:413) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309) 
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264) 
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:141) 
                                                                            at com.ses.maintainassist.app.wind.BaseAppCompatActivity.onCreate(BaseAppCompatActivity.java:60) 
                                                                            at android.app.Activity.performCreate(Activity.java:5264) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                            at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:168) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                            at android.os.Looper.loop(Looper.java:193) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by pessonljxpd** [comment]
application 级别的 Module 可以点击 “Run” 直接跑起来，但是通过 Host 去调起得时候却不行，报了上面的异常，我看了一下宿主 LauncherActivity 继承的 AppCompatActivity 和我的 Module 中继承的 AppCompatActivity 相同，都是来自 android.support.v7.app.AppCompatActivity

**Comment by zhenglibao** [comment]
你好，请问你这个问题解决了吗？我也碰到了这个问题
