### ISSUE TITLE
迁移老项目时遇到问题。Caused by: Assertion failed:  assert (Arrays.equals(s.styleEnd, ResStringPoolSpan.END_SPAN))

### ISSUE THREAD

**Issue by chenlongkk** [wequick/Small#306]
在迁移老的项目的时候，gradle buildLib报错，能请教一下这个是什么原因导致的吗？

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':haizhisdk:lib.uicomp:processReleaseResources'.
       	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
       	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
       	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
       	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
       	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
       	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
       	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
       	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
       	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
       	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
       	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
       	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
       	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
       	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
       	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: Assertion failed:

assert (Arrays.equals(s.styleEnd, ResStringPoolSpan.END_SPAN))
               |      | |                           |
               false  | [7, 0, 0, 0, 9, 0, 0, 0]    [-1, -1, -1, -1, -1, -1, -1, -1]
                      [header:[type:1, headerSize:28, size:67544], stringCount:1940, styleCount:1, flags:256, stringsStart:7792, stylesStart:67508, stringOffsets:[0, 22, 65, 115, 164, 201, 248, 290, 326, 374, 421, 482, 542, 580, 623, 689, 734, 799, 843, 892, 938, 980, 1025, 1044, 1072, 1099, 1130, 1160, 1190, 1219, 1249, 1278, 1328, 1378, 1409, 1459, 1509, 1543, 1594, 1648, 1700, 1755, 1775, 1802, 1828, 1852, 1879, 1905, 1932, 1962, 2012, 2063, 2111, 2159, 2188, 2236, 2285, 2340, 2396, 2438, 2488, 2536, 2568, 2609, 2651, 2691, 2732, 2756, 2779, 2800, 2825, 2861, 2896, 2931, 2965, 2995, 3024, 3059, 3104, 3152, 3196, 3228, 3260, 3301, 3341, 3374, 3410, 3442, 3477, 3524, 3554, 3585, 3629, 3657, 3684, 3721, 3762, 3800, 3828, 3882, 3915, 3945, 3991, 4044, 4089, 4141, 4186, 4220, 4270, 4327, 4378, 4425, 4468, 4494, 4530, 4575, 4622, 4653, 4683, 4711, 4743, 4792, 4819, 4875, 4924, 4969, 5004, 5048, 5088, 5144, 5179, 5228, 5278, 5321, 5361, 5409, 5445, 5481, 5522, 5553, 5612, 5648, 5678, 5712, 5760, 5809, 5856, 5914, 5948, 5987, 6031, 6073, 6128, 6169, 6218, 6268, 6321, 6350, 6
                        .................................
        at net.wequick.gradle.aapt.AssetEditor.readStringPool(AssetEditor.groovy:165)
        at net.wequick.gradle.aapt.ArscEditor.readTable(ArscEditor.groovy:401)
        at net.wequick.gradle.aapt.ArscEditor.slice(ArscEditor.groovy:66)
        at net.wequick.gradle.aapt.ArscEditor$slice.call(Unknown Source)
        at net.wequick.gradle.aapt.Aapt.filterPackage(Aapt.groovy:58)
        at net.wequick.gradle.aapt.Aapt$filterPackage$3.call(Unknown Source)
        at net.wequick.gradle.AppPlugin$_hookAapt_closure50.doCall(AppPlugin.groovy:1170)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more

BUILD FAILED

Total time: 1 mins 6.271 secs

**Comment by gordonpro** [comment]
你Assets里面有些什么文件

**Comment by chenlongkk** [comment]
@gordonpro 这个lib工程本身没有assets文件夹，它的依赖是：
   compile 'com.jakewharton:butterknife:7.0.1'
    compile files('libs/ZXing-3.2.1.jar')
    compile 'com.facebook.fresco:animated-gif:0.11.0'
    compile 'com.facebook.fresco:fresco:0.11.0'
    compile 'com.android.support:design:23.4.0'
    compile "com.android.support:appcompat-v7:23.4.0"
    compile "com.android.support:cardview-v7:23.4.0"

**Comment by galenlin** [comment]
@chenlongkk 这个是Small在解析arsc文件时报错了，方便的话把工程发我看下

**Comment by chenlongkk** [comment]
@galenlin 似乎是buildTools的版本问题，报错的版本是23.0.3，我换成23.0.1后就不报错了。
