### ISSUE TITLE
还是混淆的问题

### ISSUE THREAD

**Issue by 601367322** [wequick/Small#331]
宿主开启混淆之后报错，找不到插件的MainActivity

 Process: com.prance.app, PID: 12492
                                                                java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.prance.app/com.prance.plugin.app.youzan.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.prance.plugin.app.youzan.MainActivity" on path: DexPathList[[zip file "/data/app/com.prance.app-1/lib/arm/libcom_prance_plugin_app_youzan.so", zip file "/data/app/com.prance.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.prance.app-1/lib/arm, /vendor/lib, /system/lib]]
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2546)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5972)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.prance.plugin.app.youzan.MainActivity" on path: DexPathList[[zip file "/data/app/com.prance.app-1/lib/arm/libcom_prance_plugin_app_youzan.so", zip file "/data/app/com.prance.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.prance.app-1/lib/arm, /vendor/lib, /system/lib]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                    at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2536)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758) 
                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:145) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5972) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
                                                                	Suppressed: java.lang.NoClassDefFoundError: com.prance.plugin.app.youzan.MainActivity
                                                                    at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                    at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                    at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                    at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                    		... 14 more
                                                                	Suppressed: java.lang.ClassNotFoundException: com.prance.plugin.app.youzan.MainActivity
                                                                    at java.lang.Class.classForName(Native Method)
                                                                    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                    		... 13 more
                                                                 Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by 601367322** [comment]
原因可能是，双方都引用了同一个公共库

**Comment by 601367322** [comment]
原因可能是引用了同一个公共库

**Comment by 601367322** [comment]
compile project 只能引用一个插件式的lib吗

**Comment by 601367322** [comment]
找到原因了，开启混淆之后，只能引用lib.*格式的模块

**Comment by 601367322** [comment]
问题不够明确，已关闭
