### ISSUE TITLE
在S7 edge 6.0.1上，第一次安装没问题，杀死再进报错

### ISSUE THREAD

**Issue by 601367322** [wequick/Small#334]
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.prance.app/com.prance.app.ui.home.HomeActivity}: android.content.res.Resources$NotFoundException: Resource ID #0xe91560b0
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
3 ......
4 Caused by:
5 android.content.res.Resources$NotFoundException:Resource ID #0xe91560b0
6 android.content.res.Resources.getValue(Resources.java:2558)
7 android.content.res.Resources.loadXmlResourceParser(Resources.java:4364)
8 android.content.res.Resources.getLayout(Resources.java:2372)
9 android.view.LayoutInflater.inflate(LayoutInflater.java:427)
10 android.view.LayoutInflater.inflate(LayoutInflater.java:380)
11 android.view.View.inflate(View.java:21162)
12 com.prance.base.ui.BaseActivity.setContentView(SourceFile:120)
13 com.prance.base.ui.BaseActivity.onCreate(SourceFile:78)
14 android.app.Activity.performCreate(Activity.java:6876)
15 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
16 net.wequick.small.b$c.callActivityOnCreate(SourceFile:167)
17 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
18 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
19 android.app.ActivityThread.access$1100(ActivityThread.java:221)
20 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
21 android.os.Handler.dispatchMessage(Handler.java:102)
22 android.os.Looper.loop(Looper.java:158)
23 android.app.ActivityThread.main(ActivityThread.java:7233)
24 java.lang.reflect.Method.invoke(Native Method)
25 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
26 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by 601367322** [comment]
三星S4 5.0.1没有问题

**Comment by 601367322** [comment]
net.wequick.small.b$c.callActivityOnCreate(SourceFile:167)

**Comment by galenlin** [comment]
这是你混淆过了，在源码ApkBundleLauncher里。
你调试下该类下的 `postSetUp` 方法看看 `ReflectAccelerator.mergeResources(app, paths);` 是否执行异常。

**Comment by 601367322** [comment]
FATAL EXCEPTION: main
                                                              Process: com.prance.app, PID: 8018
                                                              android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class com.prance.base.widget.CircleIndicator
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                  at com.prance.base.util.Utils.getInflate(Utils.java:353)
                                                                  at com.prance.base.banner.BannerHolder.<init>(BannerHolder.java:31)
                                                                  at com.prance.app.ui.home.HomeAdapter.onCreate(HomeAdapter.java:17)
                                                                  at com.prance.base.ui.BaseLoadMoreAdapter.onCreateViewHolder(BaseLoadMoreAdapter.java:75)
                                                                  at com.prance.base.ui.BaseLoadMoreAdapter.onCreateViewHolder(BaseLoadMoreAdapter.java:18)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5836)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5060)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at com.prance.base.widget.pull.swipe.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:604)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1197)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:391)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                              	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.

**Comment by 601367322** [comment]
不开混淆，调试状态下，也会出问题，我再看看

**Comment by 601367322** [comment]
调试每次都成功，但是不调试的时候，将应用从后台杀死，再打开就会出这个错误。无解。。。

**Comment by sampsonhuang93** [comment]
请问这个问题解决了吗

**Comment by 601367322** [comment]
还没，demo没问题，估计是我项目的问题
