### ISSUE TITLE
App crash when setting a drawable as background.

### ISSUE THREAD

**Issue by sampsonhuang93** [wequick/Small#335]
我在子app module中的一个layout文件中给Button设置了background, 代码如下:

```
     <Button
            android:id="@+id/login_submit"
            android:layout_width="@dimen/margin_540px"
            android:layout_height="@dimen/margin_90px"
            android:layout_marginTop="@dimen/margin_130px"
            android:background="@drawable/bg_text_white_login"
            android:gravity="center"
            android:text="@string/login_submit"
            android:textColor="@drawable/bg_text_white_login"
            android:textAllCaps="false"
            android:textSize="@dimen/size_36px"/>
```

drawable bg_text_white_login如下：

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">

    <!-- disabled -->
    <item android:state_enabled="false" android:color="@color/common_text_gray"/>

    <!-- default -->
    <item android:color="@color/white"/>

</selector>
```

报错信息：

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{***.MainActivity}: android.view.InflateException: Binary XML file line #175: Error inflating class Button
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:178)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                           at android.os.Looper.loop(Looper.java:194)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5631)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

**Comment by chykidd** [comment]
@sampsonhuang93  log是不是不全，我也遇到了，log显示根本原因是StringBlock.nativeGetString(-2) 越界了，我是TextView设置background崩溃了，也是自己写的xml

**Comment by sampsonhuang93** [comment]
@chykidd, 我只选了一部分log, 我现在给一个app module中的布局设置mipmap背景都报错，也是同样的问题，不知道怎么解决。

**Comment by chykidd** [comment]
@sampsonhuang93  现象看起来我们是一样的问题，textview设置background的时候出错，不知道你的log里的崩溃原因是不是framework里的StringBlock.nativeGetString越界问题

**Comment by sampsonhuang93** [comment]
@chykidd, 我的错误信息是这样的

```
FATAL EXCEPTION: main
     Process: com.***.***_small, PID: 4136
     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.***.***_small/com.***.app.login.LoginActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.widget.RelativeLayout
         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
         at android.app.ActivityThread.access$800(ActivityThread.java:178)
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
         at android.os.Handler.dispatchMessage(Handler.java:111)
         at android.os.Looper.loop(Looper.java:194)
         at android.app.ActivityThread.main(ActivityThread.java:5631)
         at java.lang.reflect.Method.invoke(Native Method)
         at java.lang.reflect.Method.invoke(Method.java:372)
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
      Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.widget.RelativeLayout
         at android.view.LayoutInflater.createView(LayoutInflater.java:633)
         at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
         at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
         at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
         at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
         at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
         at com.***.app.login.LoginActivity.onCreate(LoginActivity.java:79)
         at android.app.Activity.performCreate(Activity.java:6092)
         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
         at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:167)
         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
         at android.app.ActivityThread.access$800(ActivityThread.java:178) 
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
         at android.os.Handler.dispatchMessage(Handler.java:111) 
         at android.os.Looper.loop(Looper.java:194) 
         at android.app.ActivityThread.main(ActivityThread.java:5631) 
         at java.lang.reflect.Method.invoke(Native Method) 
         at java.lang.reflect.Method.invoke(Method.java:372) 
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
      Caused by: java.lang.reflect.InvocationTargetException
         at java.lang.reflect.Constructor.newInstance(Native Method)
         at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
         at android.view.LayoutInflater.createView(LayoutInflater.java:607)
         at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
         at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
         at android.view.LayoutInflater.inflate(LayoutInflater.java:482) 
         at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
         at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
         at com.***.app.login.LoginActivity.onCreate(LoginActivity.java:79) 
         at android.app.Activity.performCreate(Activity.java:6092) 
         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
         at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:167) 
         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468) 
         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
         at android.app.ActivityThread.access$800(ActivityThread.java:178) 
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
         at android.os.Handler.dispatchMessage(Handler.java:111) 
         at android.os.Looper.loop(Looper.java:194) 
         at android.app.ActivityThread.main(ActivityThread.java:5631) 
         at java.lang.reflect.Method.invoke(Native Method) 
         at java.lang.reflect.Method.invoke(Method.java:372) 
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
      Caused by: java.lang.IndexOutOfBoundsException
         at android.content.res.StringBlock.nativeGetString(Native Method)
         at android.content.res.StringBlock.get(StringBlock.java:107)
         at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:277)
         at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:996)
         at android.content.res.TypedArray.getValueAt(TypedArray.java:982)
         at android.content.res.TypedArray.getDrawable(TypedArray.java:745)
         at android.view.View.<init>(View.java:3791)
         at android.view.ViewGroup.<init>(ViewGroup.java:524)
         at android.widget.RelativeLayout.<init>(RelativeLayout.java:267)
         at android.widget.RelativeLayout.<init>(RelativeLayout.java:263)
         at android.widget.RelativeLayout.<init>(RelativeLayout.java:259)
         at java.lang.reflect.Constructor.newInstance(Native Method) 
         at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
         at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
         at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
         at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
         at android.view.LayoutInflater.inflate(LayoutInflater.java:482) 
         at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
         at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
         at com.***.app.login.LoginActivity.onCreate(LoginActivity.java:79) 
         at android.app.Activity.performCreate(Activity.java:6092) 
         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
         at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:167) 
         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468) 
         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
         at android.app.ActivityThread.access$800(ActivityThread.java:178) 
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
         at android.os.Handler.dispatchMessage(Handler.java:111) 
         at android.os.Looper.loop(Looper.java:194) 
         at android.app.ActivityThread.main(ActivityThread.java:5631) 
         at java.lang.reflect.Method.invoke(Native Method) 
         at java.lang.reflect.Method.invoke(Method.java:372) 
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
```

**Comment by chykidd** [comment]
@sampsonhuang93 

是一样的问题，这个很奇怪啊，个别的background设置就报错，还请大神看看咋回事啊
@galenlin 
 
Caused by: java.lang.IndexOutOfBoundsException
         at android.content.res.StringBlock.nativeGetString(Native Method)

**Comment by chykidd** [comment]
@sampsonhuang93   方便提供个必然出错的demo么？ 发个下载地址，一起看下问题

**Comment by jasonrongdevelop** [comment]
也遇到相同的问题，也是xml的drawable， 追踪到是 String styleTag = nativeGetString(mNative, styleId);

**Comment by jasonrongdevelop** [comment]
@chykidd 这个问题找到原因了吗？

**Comment by dengyin2000** [comment]
我也遇到类似的问题，但不是必现，公司的项目太大，几百M， @chykidd

**Comment by chenyanmo** [comment]
在 module里面的资源不能用selector吗？

**Comment by dengyin2000** [comment]
没人解决吗？

**Comment by jarvan11** [comment]
时不时会遇到，挺蛋疼的问题，有解决方案吗？

**Comment by WayJ** [comment]
@dengyin2000 @jarvan11 
同样遇到这个问题，将资源文件放在sample中无法重现。
small 1.2.0-bate2
手机 Sony LT26I ，Android 4.1 。

找到一个零时解决方案，将资源文件放到app+stub中，就可以不会报错。期望大神能够更好的解决这个问题。

**Comment by galenlin** [comment]
谁提供一个demo给我调试下，谢谢

**Comment by johnx4** [comment]
@galenlin  demo比较难提供，说一下问题产生的原因，希望修正。
AssetEditor中的filterStringPool函数并没有对StringPoolSpan进行重新处理，导致stringpoolspan的name字段还是原stringpool的index，但现stringpool经过剪切数组长度已经没那么大了，因此导致了IndexOutOfBoundsException的错误

**Comment by galenlin** [comment]
#441 这个PR吗？如何重现呢？我需要验证下。

**Comment by chykidd** [comment]
同意上面的意见，StringPoolSpan 的index错误，主要是value字符串中存在自定义属性

**Comment by johnx4** [comment]
@galenlin 在strings.xml加入类似<b> </b>的用法，应该可以复现

**Comment by johnx4** [comment]
@galenlin 在string.xml加入"<b></b>"等类似用法应该可以重现

**Comment by johnx4** [comment]
@galenlin 在strings.xml加入`<b></b>`等类似用法应该可以重现

**Comment by WayJ** [comment]
@galenlin 
测试环境：
small 1.2.0-bate2
手机 Sony LT26I ，Android 4.1 。

出错步骤：
进入登陆页面后，点击帐号的输入框会报错。
点击输入框时会调用到一个drawable资源，就会报IndexOutOfBoundsException错。
问题可能与在app.main里资源color文件夹下的3个selector 有关，试过将其放入drawable中就不会报错。在Sample中无法重现

由于回复中一直无法成功添加附件，已将报错demo发了一份到您的邮箱，
同时在百度网盘共享了一份 https://pan.baidu.com/s/1o88rNK2

**Comment by galenlin** [comment]
@WayJ 好的 👍
