### ISSUE TITLE
demo工程在7.0的机器上crash。

### ISSUE THREAD

**Issue by chenlongkk** [wequick/Small#347]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

我编译Small的demo工程，在7.0的机器上，首先打开 web.about页面，然后打开app.detail页面，程序crash

## 你期望的结果是什么？

app.detail页面的能正常打开

## 实际结果是什么？

程序crash
```
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
  at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:340)
  at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:309)
  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:273)
  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
  at net.wequick.example.small.app.detail.MainActivity.onCreate(MainActivity.java:20)

```
### Compile-time

```
  gradle-small plugin : 1.0.0-beta9 (project)
            small aar : 1.1.0-beta5 (project)
          gradle core : 2.13
       android plugin : 2.1.2
                   OS : Mac OS X 10.11.2 (x86_64)
```

### Runtime

```
  Device : Nexus 5x
     SDK : Android 7.0
```

**Comment by galenlin** [comment]
感谢反馈，请更新最新的代码，确认在根`build.gradle`中包含了统一环境配置：

```
small {
    android {
        compileSdkVersion = 23
        buildToolsVersion = "23.0.3"
        supportVersion = "23.4.0"
    }
}
```

在用 `./gradlew small` 检查环境，你看到的应该是：

### Compile-time

```
  gradle-small plugin : 1.1.0-beta1 (maven)
            small aar : 1.1.0-beta6 (maven)
          gradle core : 2.10
       android plugin : 2.1.2
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

| type |         name          |  PP  | sdk |  aapt  | support | file(armeabi)  |   size   |
|------|-----------------------|------|-----|--------|---------|----------------|----------|
| host | app                   |      | 23  | 23.0.3 | 23.4.0  |                |          |
| stub | app+stub              |      | 23  | 23.0.3 | 23.4.0  |                |          |
| app  | app.main              | 0x77 | 23  | 23.0.3 | 23.4.0  | *_main.so      | 10.9 KB  |
| app  | app.available-if-stub | 0x4e | 23  | 23.0.3 |         | *_stub.so      | 18.8 KB  |
| app  | app.mine              | 0x16 | 23  | 23.0.3 |         | *_mine.so      | 35.5 KB  |
| app  | app.detail            | 0x67 | 23  | 23.0.3 | 23.4.0  | *_detail.so    | 6.6 KB   |
| app  | app.home              | 0x70 | 23  | 23.0.3 |         | *_home.so      | 10.4 KB  |
| lib  | lib.analytics         | 0x76 | 23  | 23.0.3 |         | *_analytics.so | 125.7 KB |
| lib  | lib.utils             | 0x73 | 23  | 23.0.3 | 23.4.0  | *_utils.so     | 5.8 KB   |
| lib  | lib.style             | 0x79 | 23  | 23.0.3 | 23.4.0  | *_style.so     | 4.6 KB   |
| web  | web.about             |      | 23  | 23.0.3 | 23.4.0  | *_about.so     | 24.3 KB  |

注意其中的 `sdk`, `aapt`, `support` 版本应该是保持一致的。

通过 `git status Sample` 来查看 `public.txt` 是否因曾经的“Support包版本不一致”而产生了变化，如果是的话，使用 `git checkout [path-to-public.txt]` 来撤销改变。

最后使用 `./gradlew cleanLib`, `buildLib`, `cleanBundle`, `buildBundle` 重新编译一遍，问题应该能够得到解决。

**Comment by galenlin** [comment]
@chenlongkk Sorry没看清你的问题。你的问题描述应该加上：

*直接打开app.detail没问题*

这个信息的缺失让我产生了误解，😂。

我在7.0下试验了下，确实从网页Activity启动插件会有问题，我再认真看下。。

**Comment by chenlongkk** [comment]
@galenlin  似乎和webview有关，我在Small初始化之前，先初始化一个webview，就可以正常打开app.detail

**Comment by galenlin** [comment]
@chenlongkk 是的，我调试了下：
```java
public WebView(Context context) {
        super(context);
        initSettings(); // <- 走到这句时application的assets被重置了
    }
```

我刚试了在其后重新恢复插件assets，可以正常启动app.detail了，不过碰到一些别的crash。

你刚才的尝试我认为会是一个更好的解决方案，我试下在WebBundleLaucher setUp时创建一个webview。
