### ISSUE TITLE
为什么 Sample 工程 总跑不起来？You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by pessonljxpd** [wequick/Small#361]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

我在 AndroidStudio 中跑 Sample 工程，尝试了修改 app.main 工程中 MainActivity 的 theme 的 parent,但结果总是报错

## 你期望的结果是什么？

Small能够正确运行。

## 实际结果是什么？

Small发生运行报错，报错信息如下：

	java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.example.small.app.main.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2341)
	                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
	                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:154)
	                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
	                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
	                                                                               at android.os.Looper.loop(Looper.java:135)
	                                                                               at android.app.ActivityThread.main(ActivityThread.java:5298)
	                                                                               at java.lang.reflect.Method.invoke(Native Method)
	                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
	                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
	                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
	                                                                            Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	                                                                               at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
	                                                                               at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
	                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
	                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	                                                                               at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:67)

### Compile-time

	gradle-small plugin : 1.1.0-beta3 (maven)
	        small aar : 1.1.0-beta9 (maven)
	      gradle core : 2.14.1
	   android plugin : 2.2.2
	               OS : Windows 8.1 6.3 (amd64)

### Bundles
| type |      name      |  PP  | sdk |  aapt  | support | file(armeabi)  |    size      |
|------|----------------|------|-----|--------|---------|----------------|--------------|
| host | app            |      | 23  | 23.0.3 | 23.4.0  |                |  			|
| stub | app+stub       |      | 23  | 23.0.3 | 23.4.0  |                | 				|
| app  | app.main       | 0x77 | 23  | 23.0.3 | 23.4.0  | *_main.so      | 11.5 KB      |
| app  | app.mine       | 0x16 | 23  | 23.0.3 |         | *_mine.so      | 36.3 KB 		|
| app  | app.ok-if-stub | 0x6a | 23  | 23.0.3 |         | *_stub.so      | 21.1 KB  		|
| app  | app.detail     | 0x67 | 23  | 23.0.3 |         | *_detail.so    | 7.6 KB  		|
| app  | app.home       | 0x70 | 23  | 23.0.3 |         | *_home.so      | 11.4 KB  	|
| lib  | lib.analytics  | 0x76 | 23  | 23.0.3 |         | *_analytics.so | 127.1 KB  	|
| lib  | lib.utils      | 0x73 | 23  | 23.0.3 | 23.4.0  | *_utils.so     | 1 MB  		|
| lib  | lib.style      | 0x79 | 23  | 23.0.3 | 23.4.0  | *_style.so     | 1,006.8 KB 	|
| web  | web.about      |      | 23  | 23.0.3 | 23.4.0  | *_about.so     | 24.3 KB  	|

（注：编译时错误只需本行以上内容，运行时错误补充本行以下内容）
### Runtime

```
  Device : Xiaomi note 
     SDK : Android 5.1.1
     ABI : armeabi-v7a
```

**Comment by galenlin** [comment]
从编译结果看 `lib.utils.so` -> 1MB， `lib.style.so` -> 1006.8KB偏大了，可能是误将AppCompat打包进去了（编译的偶发问题，暂未查明原因）。

你用 `git diff` 命令看下是否 `lib.utils/public.txt`, `lib.style/public.txt` 被修改了。

再使用 `git checkout [path-to-public.txt]` 来撤销修改。

最后cleanLib/buildLib/cleanBundle/buildBundle重编下。（正常的大小应该在几十k）

**Comment by pessonljxpd** [comment]
我尝试修改了 lib.style 中 values/styles.xml 和 values-v21/styles.xml 的相关内容后，Sample 工程可以正常运行了。

具体结果如下：

###values/styles.xml###

 	
    <style name="AppTheme.Base" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

    <style name="AppTheme.NoActionBar" parent="AppTheme.Base">
        
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>

###values-v21/styles.xml###

	<style name="AppTheme.NoActionBar" parent="AppTheme.Base">
	    <item name="windowActionBar">false</item>
	    <item name="windowNoTitle">true</item>
	    <item name="android:windowDrawsSystemBarBackgrounds">true</item>
	    <item name="android:statusBarColor">@android:color/transparent</item>
	</style>


相应地所有引用的 lib.style 的插件修改到新的 theme 名称即可。
