### ISSUE TITLE
自定义View添加自定义属性使用报错

### ISSUE THREAD

**Issue by dxiaogang** [wequick/Small#39]
如题.

**Comment by galenlin** [comment]
gradle-small是否已使用最新版本0.2.0？

**Comment by dxiaogang** [comment]
是0.2.0,然后我跑Sample,也是同样的问题.日志如下:
 android.view.InflateException: Binary XML file line #14: Error inflating class net.wequick.example.small.lib.utils.MyTextView
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                                               at net.wequick.example.small.app.mine.MainFragment.onCreateView(MainFragment.java:16)
                                                                               at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)

我注释掉MyTextView的代码就会正常运行.

**Comment by galenlin** [comment]
检查后发现由于lib.utils在本地存在下载的更新插件包（旧版本，其中无MyTextView）造成了该问题。请先卸载安装重试。
