### ISSUE TITLE
创建公共库模块lib.utils 找不到类

### ISSUE THREAD

**Issue by kuwork** [wequick/Small#399]
宿主app在我这里，ApplicationID 和 包名不一致 
例如 
```
applicationId "com.example.mysmall"
//包名则是
com.example
```
模块app.main 则是
```
applicationId "com.example.app.main"
//包名也是
com.example.app.main
```
现在可以从宿主跳转到 app.main 的ScrollingActivity。

往下我添加一个公共库 lib.utils，包名则是
```
com.example.lib.utils
```
公共库内又一个TestUtils类:
```
import android.content.Context;
import android.widget.Toast;

public class TestUtils {
    public static void showToast(Context context,String str) {
        Toast.makeText(context,str,1000).show();
    }
}
```
在ScrollingActivity 调用这个showToast方法，会出错，直接提示
```
01-13 13:47:15.038 28018-28018/com.example.mysmall E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.mysmall, PID: 28018
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/example/lib/utils/TestUtils;
    at com.example.app.main.ScrollingActivity$1.onClick(ScrollingActivity.java:27)
    at android.view.View.performClick(View.java:4785)
    at android.view.View$PerformClick.run(View.java:19919)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5433)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.lib.utils.TestUtils" on path: DexPathList[[zip file "/data/app/com.example.mysmall-2/lib/arm/libcom_example_app_main.so", zip file "/data/app/com.example.mysmall-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.mysmall-2/lib/arm, /vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    at com.example.app.main.ScrollingActivity$1.onClick(ScrollingActivity.java:27) 
    at android.view.View.performClick(View.java:4785) 
    at android.view.View$PerformClick.run(View.java:19919) 
    at android.os.Handler.handleCallback(Handler.java:739) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5433) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.example.lib.utils.TestUtils" on path: DexPathList[[dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-support-annotations-25.1.0_ae47dab1e4773f2211807dd758961395656e8adb-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-net.wequick.small-small-1.1.0-alpha1_766d70e39212718d6e1d7dbbdcfa4a302fae2947-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-com.android.support-transition-25.1.0_435524df04eabef2e7cbacb1f4ddde2fe9e50cbe-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.1.0_e1607a854baea15d9a5fc20cdd8239c6059c1afd-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-com.android.support-support-v4-25.1.0_c548cf5ee12cb0cb0e3247d5d2ab6418eb84fa57-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-com.android.support-support-media-compat-25.1.0_2ebd33fd19d19d119844b06421bae0859bc87be9-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-com.android.support-support-fragment-25.1.0_3706fe1fa0dca1e49ca8f08f81cf70c67368a634-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-com.android.support-support-core-utils-25.1.0_737639ce80997396509e71c5904dc9051b1c4d76-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-com.android.support-support-core-ui-25.1.0_d53396f7e370d0b725eb45c752aa4567855c30ce-classes.dex", dex file "/data/data/com.example.mysmall/files/instant-run/dex/slice-com.android.support-support-compat-25.1.0_56e00578ea20b9087c135bf69975facac4af5384-classes.dex", dex file "/data
```
## 希望结果
能够顺利执行showToast方法

## 疑问
Small 对模块命名的限制已经很明了，但是包名只是看到需要含有 ".app."或者".lib."等，我上面那种写法是否有问题？

**Comment by MaYunFei** [comment]
@kuwork 为什么关闭了怎么解决的，新版本已经支持自定义包名了

**Comment by MaYunFei** [comment]
@kuwork 为什么关闭了怎么解决的，新版本已经支持自定义包名了

**Comment by MaYunFei** [comment]
@kuwork 为什么关闭了怎么解决的，新版本已经支持自定义包名了

**Comment by MaYunFei** [comment]
@kuwork 为什么关闭了怎么解决的，新版本已经支持自定义包名了

**Comment by kuwork** [comment]
@MaYunFei 我也是后来发现支持自定义包名的，但是我当时的确是通过bundle.json声明解决的。吃一堑长一智

**Comment by xunuosi** [comment]
@kuwork 我也是在报NoClassDefFoundError这个错误 请问你是怎么解决的啊？bundle.json如何声明的？
