### ISSUE TITLE
Task 'lib.*' not found in root project 'Sample'

### ISSUE THREAD

**Issue by loc1129** [wequick/Small#402]
在Sample Project中加了个插件 lib.dptest; 然后调用 gradlew buildBundle lib.dpteset aR --stacttrace, 出现如下错误，求帮忙。
* Exception is:
org.gradle.execution.TaskSelectionException: Task 'lib.dptest' not found in root project 'Sample'.
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$3.run(DefaultGradleLauncher.java:143)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:140)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)

**Comment by taoqiyang** [comment]
我也是刚看的  所以不知道说的对不对  lib.*应该是用buildLib  app才是用buildBundle吧

**Comment by loc1129** [comment]
谢谢 @taoqiyang 提醒，看了下文档，我这个编译命令用错了，应该是gradlew -p lib.dplugin aR;
不过还是报错：
* What went wrong:
Execution failed for task ':lib.dplugin:processReleaseResources'.
> java.lang.StackOverflowError (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':lib.dplugin:processReleaseResources'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.StackOverflowError
        at net.wequick.gradle.aapt.CppHexEditor.getShort(CppHexEditor.groovy:85)
        at net.wequick.gradle.aapt.CppHexEditor.readShort(CppHexEditor.groovy:79)
        at net.wequick.gradle.aapt.AssetEditor.readChunkHeader(AssetEditor.groovy:39)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:108)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)
        at net.wequick.gradle.aapt.AXmlEditor.setPackageIdRecursive(AXmlEditor.groovy:124)

**Comment by taoqiyang** [comment]
刚试了下  新建一个lib打包没问题  不过里面没加什么东西
