### ISSUE TITLE
返回退出应用，再次进入会奔溃

### ISSUE THREAD

**Issue by kuwork** [wequick/Small#404]
# 错误报告

## 你做了什么？

我添加极光推送以后遇到一个问题。我的启动过程是这样的
启动时，进入 app的LaucherActivity.然后进入app.main 的MainActivity ,并且finish掉LaucherActivity。
在MainActivity按返回，关闭App。再次打开就会异常退出。再打开一次就可以了。这个问题一定发生

## 你期望的结果是什么？

正常进入，正常启动极光推送

## 实际结果是什么？

Small发送运行报错，报错信息如下：

```
01-20 17:43:21.476 28564-28564/com.ajb.anjubao.intelligent E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.ajb.anjubao.intelligent, PID: 28564
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ajb.anjubao.intelligent/com.ajb.LaunchActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.ajb.anjubao.intelligent/com.ajb.app.introduce.IntroduceActivity}; have you declared this activity in your AndroidManifest.xml?
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2424)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2486)
    at android.app.ActivityThread.access$900(ActivityThread.java:175)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5433)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
 Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.ajb.anjubao.intelligent/com.ajb.app.introduce.IntroduceActivity}; have you declared this activity in your AndroidManifest.xml?
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1804)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
    at android.app.Activity.startActivityForResult(Activity.java:3838)
    at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
    at android.app.Activity.startActivityForResult(Activity.java:3799)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
    at net.wequick.small.BundleLauncher.launchBundle(BundleLauncher.java:180)
    at net.wequick.small.ApkBundleLauncher.launchBundle(ApkBundleLauncher.java:834)
    at net.wequick.small.Bundle.launchFrom(Bundle.java:574)
    at net.wequick.small.Small.openUri(Small.java:311)
    at net.wequick.small.Small.openUri(Small.java:293)
    at com.ajb.LaunchActivity$1.onComplete(LaunchActivity.java:55)
    at net.wequick.small.Small.setUp(Small.java:171)
    at com.ajb.LaunchActivity.onCreate(LaunchActivity.java:46)
    at android.app.Activity.performCreate(Activity.java:6083)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:220)
    at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2486) 
    at android.app.ActivityThread.access$900(ActivityThread.java:175) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5433) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
 
```

### Compile-time

```
  gradle-small plugin : 1.1.0-beta4 (project)
            small aar : 1.1.0-alpha1 (project)
          gradle core : 2.14.1
       android plugin : 2.2.3
       OS : Mac OS X 10.12 (x86_64)
```

### Runtime

```
  Device : Vivo Xplay5 Pro
     SDK : Android 5.1.1
     ABI : armeabi
```

**Comment by kuwork** [comment]
我把极光改成了分身模式。只要我在宿主的Application内执行了初始化极光。返回键退出App，再进入就一定会奔溃。
![image](https://cloud.githubusercontent.com/assets/6893350/22148627/2deb6498-df4a-11e6-84b0-0ff452344d21.png)

**Comment by kuwork** [comment]
@galenlin  会不会是这里还存在问题？[#245](https://github.com/wequick/Small/issues/245)

**Comment by kuwork** [comment]
Small.setUp 必须在LauncherActivity 内onStart()里面调用。就此结了

**Comment by MaYunFei** [comment]
@kuwork 那你之前放哪儿了

**Comment by kuwork** [comment]
@MaYunFei  onCreate 提早了。

**Comment by xiaweizi** [comment]
@kuwork 大兄弟，很想知道你的极光是怎么配置集成的？不知道该放在哪里？
