### ISSUE TITLE
 Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x73010077 a=-1}

### ISSUE THREAD

**Issue by lobo12** [wequick/Small#414]
直接运行的demo，出现这种报错：

Process: net.wequick.example.small, PID: 5417
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.example.small.app.main.MainActivity}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v7.widget.Toolbar
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2779)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5968)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
 Caused by: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v7.widget.Toolbar
    at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
    at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71)
    at android.app.Activity.performCreate(Activity.java:6366)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1124)
    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:220)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2779) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
    at android.os.Handler.dispatchMessage(Handler.java:111) 
    at android.os.Looper.loop(Looper.java:207) 
    at android.app.ActivityThread.main(ActivityThread.java:5968) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800) 
 Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class android.support.v7.widget.Toolbar
    at android.view.LayoutInflater.createView(LayoutInflater.java:651)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:770)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:844)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:804)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:804)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:804)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:521)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
    at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
    at android.app.Activity.performCreate(Activity.java:6366) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1124) 
    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:220) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2779) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
    at android.os.Handler.dispatchMessage(Handler.java:111) 
    at android.os.Looper.loop(Looper.java:207) 
    at android.app.ActivityThread.main(ActivityThread.java:5968) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800) 
 Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at android.view.LayoutInflater.createView(LayoutInflater.java:625)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:770) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:844) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:804) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:804) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:804) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
    at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
    at android.app.Activity.performCreate(Activity.java:6366) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1124) 
    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:220) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2779) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
    at android.os.Handler.dispatchMessage(Handler.java:111) 
    at android.os.Looper.loop(Looper.java:207) 
    at android.app.ActivityThread.main(ActivityThread.java:5968) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800) 
 Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x73010077 a=-1}
    at android.content.res.TypedArray.getDrawable(TypedArray.java:867)
    at android.view.View.<init>(View.java:4039)
    at android.view.ViewGroup.<init>(ViewGroup.java:599)
    at android.view.ViewGroup.<init>(ViewGroup.java:595)
    at android.support.v7.widget.Toolbar.<init>(Toolbar.java:200)
    at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
    at java.lang.reflect.Constructor.newInstance(Native Method) 
    at android.view.LayoutInflater.createView(LayoutInflater.java:625) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:770) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:844) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:804) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:804) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:804) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
    at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
    at android.app.Activity.performCreate(Activity.java:6366) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1124) 
    at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:220) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2779) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
    at android.os.Handler.dispatchMessage(Handler.java:111) 
    at android.os.Looper.loop(Looper.java:207) 
    at android.app.ActivityThread.main(ActivityThread.java:5968) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)

**Comment by galenlin** [comment]
你好，你的提问缺少运行环境，请先阅读首页贡献指南，再按照issue模板提issue。
