### ISSUE TITLE
旧手机无法启动

### ISSUE THREAD

**Issue by kuwork** [wequick/Small#423]
# 错误报告

## 你做了什么？
运行在老版本手机上异常退出

## 你期望的结果是什么？

正常启动

## 实际结果是什么？

闪退
```
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
    at com.ajb.app.utils.log.LogUtils.d(LogUtils.java:87)
    at com.ajb.app.main.MainApplication.initFresco(MainApplication.java:21)
    at com.ajb.app.main.MainApplication.onCreate(MainApplication.java:16)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1070)
    at net.wequick.small.ApkBundleLauncher$2.run(ApkBundleLauncher.java:682)
    at net.wequick.small.Bundle.postUI(Bundle.java:827)
    at net.wequick.small.ApkBundleLauncher.postSetUp(ApkBundleLauncher.java:675)
    at net.wequick.small.Bundle.loadBundles(Bundle.java:791)
    at net.wequick.small.Bundle.loadBundles(Bundle.java:297)
    at net.wequick.small.Bundle.loadLaunchableBundles(Bundle.java:231)
    at net.wequick.small.Small.setUp(Small.java:176)
    at net.wequick.small.Small.setUpOnDemand(Small.java:190)
    at net.wequick.small.ApkBundleLauncher$ActivityThreadHandlerCallback.ensureServiceClassesLoadable(ApkBundleLauncher.java:173)
    at net.wequick.small.ApkBundleLauncher$ActivityThreadHandlerCallback.handleMessage(ApkBundleLauncher.java:129)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5468)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:934)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)
    at dalvik.system.NativeStart.main(Native Method)
```

### Compile-time

```
  gradle-small plugin : 1.1.0-beta4 (project)
            small aar : 1.1.0-alpha1 (project)
          gradle core : 2.14.1
       android plugin : 2.2.3
       OS : Mac OS X 10.12 (x86_64)
```

### Runtime

```
  Device : HUAWEI G750-T00
     SDK : Android 4.2.2
     ABI : armeabi
```

**Comment by xufan** [comment]
用`gradle smallLint`命令 看看是不是有class重复了

**Comment by kuwork** [comment]
@xufan 应该不是吧，高版本手机可以跑

**Comment by bangoo1** [comment]
same issue  android4.4
