### ISSUE TITLE
java.lang.NullPointerException at net.wequick.small.AssetBundleLauncher.prelaunchBundle(AssetBundleLauncher.java:124)

### ISSUE THREAD

**Issue by tgzzl** [wequick/Small#43]
加载SD卡的插件.so资源，运行时报错：
`java.lang.NullPointerException
                                                                               at net.wequick.small.AssetBundleLauncher.prelaunchBundle(AssetBundleLauncher.java:124)
                                                                               at net.wequick.small.AssetBundleLauncher.launchBundle(AssetBundleLauncher.java:136)
                                                                               at net.wequick.small.Bundle.launchFrom(Bundle.java:357)
                                                                               at net.wequick.small.Small.openUri(Small.java:250)
                                                                               at net.wequick.small.Small.openUri(Small.java:231)

**Comment by galenlin** [comment]
为啥要加载SD卡的插件额，你这个插件不是由Small编译的吧

**Comment by galenlin** [comment]
不支持非Small编译插件。
