### ISSUE TITLE
Small.openUrl 报空指针异常

### ISSUE THREAD

**Issue by leishengwei** [wequick/Small#451]
按照官方的文档跑示例的时候,碰到的,就是下面这句话:
在app.main的MainActivity中:
```
 @Override
    protected void onStart() {
        super.onStart();
        Small.setUp(this, new Small.OnCompleteListener() {
            @Override
            public void onComplete() {
                Small.openUri("main", MainActivity.this);
            }
        });
    }
```
错误如下:
```
Process: me.leoray.smalldemo, PID: 22761
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.ConcurrentHashMap.containsKey(java.lang.Object)' on a null object reference
 at net.wequick.small.ApkBundleLauncher.prelaunchBundle(ApkBundleLauncher.java:808)
 at net.wequick.small.ApkBundleLauncher.launchBundle(ApkBundleLauncher.java:834)
 at net.wequick.small.Bundle.launchFrom(Bundle.java:563)
 at net.wequick.small.Small.openUri(Small.java:311)
 at net.wequick.small.Small.openUri(Small.java:293)
 at me.leoray.smalldemo.MainActivity$1.onComplete(MainActivity.java:26)
 at net.wequick.small.Bundle$LoadBundleHandler.handleMessage(Bundle.java:851)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5442)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by gddcs** [comment]
应该是没编译库以及bundle
