### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup

### ISSUE THREAD

**Issue by Dongzzzz** [wequick/Small#46]
```
FATAL EXCEPTION: mainb
Process: net.wequick.example.small, PID: 1206
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.small.webkit.WebActivity}: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2448)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
 at android.app.ActivityThread.access$1200(ActivityThread.java:163)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:135)
 at android.app.ActivityThread.main(ActivityThread.java:5595)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
 Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
 at android.view.ViewGroup.addView(ViewGroup.java:3790)
 at net.wequick.small.webkit.WebActivity.onCreate(WebActivity.java:104)
 at android.app.Activity.performCreate(Activity.java:6100)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
 at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:136)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2401)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
 at android.app.ActivityThread.access$1200(ActivityThread.java:163) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:135) 
 at android.app.ActivityThread.main(ActivityThread.java:5595) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:372) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```
多玩一会web.about 点进去新浪微博 多做一些操作 就会出现上面的bug

**Comment by Dongzzzz** [comment]
有的时候还会出现 UnsupportedOperationException:This isn't a hierarchical URI.
![image](https://cloud.githubusercontent.com/assets/16301715/13316551/7c505d7c-dbeb-11e5-8a62-153fc63fda30.png)

**Comment by Dongzzzz** [comment]
问题手机:华为荣耀6. 系统版本:EMUI3.1 。 android版本:5.1.1

**Comment by galenlin** [comment]
small:1.0.0 已解决，关闭本问题
