### ISSUE TITLE
调用第三方库，如果代码中访问了R文件会出现NoClassDefFoundError

### ISSUE THREAD

**Issue by linchaolong** [wequick/Small#461]
在lib.*中 `compile 'com.linchaolong.android:imagepicker:1.1'`，调用 startChooser 接口，在该接口中访问库中的一个 string 资源的地方 crash 了，但是运行单个模块没有问题，和 [issues 194](https://github.com/wequick/Small/issues/194) 类似。错误日志如下：

```
04-19 17:06:22.514 22652-22652/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: net.wequick.example.small, PID: 22652
                                                                           java.lang.NoClassDefFoundError: com.linchaolong.android.imagepicker.R$string
                                                                               at com.linchaolong.android.imagepicker.ImagePicker.getTitle(ImagePicker.java:147)
                                                                               at com.linchaolong.android.imagepicker.ImagePicker.startChooser(ImagePicker.java:87)
                                                                               at net.wequick.example.small.app.home.MainFragment$6.onClick(MainFragment.java:90)
                                                                               at android.view.View.performClick(View.java:4444)
                                                                               at android.view.View$PerformClick.run(View.java:18440)
                                                                               at android.os.Handler.handleCallback(Handler.java:733)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                                               at dalvik.system.NativeStart.main(Native Method)
04-19 17:06:22.525 22652-22652/net.wequick.example.small I/Process: Sending signal. PID: 22652 SIG: 9

```

环境说明：
```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'net.wequick.tools.build:gradle-small:1.2.0-beta3'
    }
}

apply plugin: 'net.wequick.small'

small {
    buildToAssets = false
    aarVersion = '1.2.0-beta3'
    android {
        compileSdkVersion = 25
        buildToolsVersion = "25.0.2"
        supportVersion = "25.1.0"
    }
}
```

**Comment by linchaolong** [comment]
代码已提交 https://github.com/linchaolong/Small，麻烦看一下，thx。

**Comment by poovarasanvasudevan** [comment]
Is this fixed... I am also getting this issue

**Comment by xufan** [comment]
Looks like it's a Bug  in `AppPlugin.groovy`
The collect method `prepareSplit`'s `transitiveVendorAars` didn't add aar correct to generating R.java . @galenlin

**Comment by galenlin** [comment]
Works for _MAC_. 😕  I had reproduced it on _Windows_, fixing it.

**Comment by galenlin** [comment]
@xufan It's also caused by the`buildCache` feature rolled in `Android Plugin 2.3.0`.
I saw the PR #467, seems to fix this?

**Comment by poovarasanvasudevan** [comment]
Is this fixed I am Still getting this

**Comment by galenlin** [comment]
@poovarasanvasudevan use 1.2.0-beta5 for a try

**Comment by anmingyu11** [comment]
似乎所有的第三方库的引入都会有这种情况，只要有资源id，包括databinding
