### ISSUE TITLE
RootPlugin nullPointException 

### ISSUE THREAD

**Issue by aheadlcx** [wequick/Small#469]
测试 demo 
https://github.com/aheadlcx/TestSmall
在 sample 以及测试 demo 都可以重现。./gradlew buildlib --stacktrace 即可看到。

**在 右上角的 Gradle 里面选择 gradle task buildLib 没有报 error ，并且可以生成对应的 so**
log 如下

````java
':app:buildLib'


* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:buildLib'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException: Cannot get property 'packageOutputFile' on null object
        at net.wequick.gradle.RootPlugin.buildLib(RootPlugin.groovy:469)
        at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:453)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:405)
        at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
        at net.wequick.gradle.RootPlugin$_configureProject_closure1$_closure20$_closure24.doCall(RootPlugin.groovy:119)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:596)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:577)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 20 more



````

**Comment by galenlin** [comment]
是不是配置了并行编译， `./gradlew buildLib -q -Dorg.gradle.parallel=false` 试试

**Comment by aheadlcx** [comment]
@galenlin 还真是。咨询一下，造成这个 空指针，是不是可以理解为，aapt 是单例的么。

编译过后，运行到 手机上。会出现另外一个问题。解析 xml 找不到 view。麻烦您了。

log 如下  

````java
FATAL EXCEPTION: main
                                                                        Process: me.aheadlcx.test.small, PID: 31742
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{me.aheadlcx.test.small/me.aheadlcx.app.main.MainActivity}: android.view.InflateException: Binary XML file line #14: Error inflating class android.widget.Button
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                         Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class android.widget.Button
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:642)
                                                                            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
                                                                            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:727)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:786)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:851)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:510)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:420)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:371)
                                                                            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:412)
                                                                            at android.app.Activity.setContentView(Activity.java:2180)
                                                                            at me.aheadlcx.app.main.MainActivity.onCreate(MainActivity.java:15)
                                                                            at android.app.Activity.performCreate(Activity.java:6083)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
                                                                            at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:221)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:616)
                                                                            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
                                                                            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:727) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:786) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:851) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:510) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
                                                                            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:412) 
                                                                            at android.app.Activity.setContentView(Activity.java:2180) 
                                                                            at me.aheadlcx.app.main.MainActivity.onCreate(MainActivity.java:15) 
                                                                            at android.app.Activity.performCreate(Activity.java:6083) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115) 
                                                                            at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:221) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                                                                         Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 6
                                                                            at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
                                                                            at android.widget.TextView.<init>(TextView.java:747)
                                                                            at android.widget.Button.<init>(Button.java:111)
                                                                            at android.widget.Button.<init>(Button.java:107)
                                                                            at android.widget.Button.<init>(Button.java:103)
                                                                            at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:616) 
                                                                            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
                                                                            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:727) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:786) 
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:851) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:510) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
                                                                            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:412) 
                                                                            at android.app.Activity.setContentView(Activity.java:2180) 
                                                                            at me.aheadlcx.app.main.MainActivity.onCreate(MainActivity.java:15) 
                                                                            at android.app.Activity.performCreate(Activity.java:6083) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115) 
                                                                            at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:221) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
````

**Comment by galenlin** [comment]
buildLib有顺序要求，只能串行编译。你看下首页的贡献指南，把环境补充下。

**Comment by aheadlcx** [comment]
# 在测试demo 中 ，环境如下

```
  gradle-small plugin : 1.2.0-beta3 (maven)
            small aar : 1.2.0-beta3 (maven)
          gradle core : 3.3
       android plugin : 2.3.1
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

| type |   name   |  PP  | sdk |  aapt  | support | file(armeabi) |  size  |
|------|----------|------|-----|--------|---------|---------------|--------|
| host | app      |      | 25  | 25.0.2 | 25.1.0  |               |        |
| app  | app.main | 0x77 | 25  | 25.0.2 |         | *_main.so     | 6.4 KB |
| app  | app.home | 0x70 | 25  | 25.0.2 |         | *_home.so     | 6.1 KB |
| lib  | lib.ui   | 0x31 | 25  | 25.0.2 | 25.1.0  | *_ui.so       | 1.1 MB |


Android Studio 2.3.1 正式版


# 在 sample 中同样可以重现。
有2个情况：  
1. 目前 sample 中，会出现 theme.AppCompat  的问题。
2. 后面将 AppCompatActivity 改成 FragmentActivity ，也会出现 xml 解析不到 view 的情况。

在 sample 的环境如下

### Compile-time

```
  gradle-small plugin : 1.2.0-beta3 (maven)
            small aar : 1.2.0-beta3 (maven)
          gradle core : 3.3
       android plugin : 2.3.0
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

| type |      name      |  PP  | sdk |  aapt  | support | file(armeabi)  |  size   |
|------|----------------|------|-----|--------|---------|----------------|---------|
| host | app            |      | 25  | 25.0.2 | 25.1.0  |                |         |
| stub | app+stub       |      | 25  | 25.0.2 | 25.1.0  |                |         |
| app  | app.main       | 0x77 | 25  | 25.0.2 | 25.1.0  | *_main.so      | 11.7 KB |
| app  | app.mine       | 0x16 | 25  | 25.0.2 |         | *_mine.so      | 47.6 KB |
| app  | app.ok-if-stub | 0x6a | 25  | 25.0.2 |         | *_stub.so      | 19.7 KB |
| app  | app.detail     | 0x67 | 25  | 25.0.2 | 25.1.0  | *_detail.so    | 7.4 KB  |
| app  | app.home       | 0x70 | 25  | 25.0.2 |         | *_home.so      | 11.3 KB |
| lib  | lib.analytics  | 0x76 | 25  | 25.0.2 |         | *_analytics.so | 1.2 MB  |
| lib  | lib.utils      | 0x73 | 25  | 25.0.2 | 25.1.0  | *_utils.so     | 1.1 MB  |
| lib  | lib.style      | 0x79 | 25  | 25.0.2 | 25.1.0  | *_style.so     | 1.1 MB  |
| web  | web.about      |      | 25  | 25.0.2 | 25.1.0  | *_about.so     | 24.3 KB |


BUILD SUCCESSFUL

## 情况 1  的 log 如下

````java
 Process: net.wequick.example.small, PID: 3535
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.example.small.app.main.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                          Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:355)
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:324)
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:285)
                                                                             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                                             at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71)
                                                                             at android.app.Activity.performCreate(Activity.java:6083)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
                                                                             at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:221)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
````

## 情况 2 
 log 如下

````java
 FATAL EXCEPTION: main
                                                                         Process: net.wequick.example.small, PID: 7296
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.example.small.app.main.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                          Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:642)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:488)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:420)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:371)
                                                                             at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:412)
                                                                             at android.app.Activity.setContentView(Activity.java:2180)
                                                                             at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71)
                                                                             at android.app.Activity.performCreate(Activity.java:6083)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
                                                                             at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:221)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:616)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:488) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
                                                                             at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:412) 
                                                                             at android.app.Activity.setContentView(Activity.java:2180) 
                                                                             at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
                                                                             at android.app.Activity.performCreate(Activity.java:6083) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115) 
                                                                             at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:221) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
                                                                          Caused by: java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
                                                                             at android.support.design.widget.ThemeUtils.checkAppCompatTheme(ThemeUtils.java:36)
                                                                             at android.support.design.widget.CoordinatorLayout.<init>(CoordinatorLayout.java:206)
                                                                             at android.support.design.widget.CoordinatorLayout.<init>(CoordinatorLayout.java:200)
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:616) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:488) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:420) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:371) 
                                                                             at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:412) 
                                                                             at android.app.Activity.setContentView(Activity.java:2180) 
                                                                             at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71) 
                                                                             at android.app.Activity.performCreate(Activity.java:6083) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115) 
                                                                             at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:221) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                             at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5418) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
````

Thanks in advance .

**Comment by aheadlcx** [comment]
最后一个问题，删除 public.txt 之后，就可以了。Thx

**Comment by iFarSeer** [comment]
public.txt 在哪里？
