### ISSUE TITLE
gradlew buildBundle -q (Unexpected failure during lint analysis of LoginActivity.java (this is a bug in lint or one of the libraries it depends on))

### ISSUE THREAD

**Issue by linhongbao** [wequick/Small#474]
错误报告

你做了什么？

gradlew buildBundle -q

你期望的结果是什么？

我期望这个插件能正常编译成功。

实际结果是什么？

Small发生编译报错，报错信息如下： 
F:\Android\test\Tone>gradlew buildBundle -q
  Small building bundle 1 of 1 - app.main (0x77)
        [app.main] split library res files...                           [  OK  ]
        [app.main] slice asset package and reset package id...          [  OK  ]
        [app.main] split library R.java files...                        [  OK  ]
        [app.main] split R.class...                                     [  OK  ]
Unexpected failure during lint analysis of LoginActivity.java (this is a bug in lint or one of the libraries it depends on)
                                                                                                                            AbortCompilation:ProblemHandler.handle(ProblemHandler.java:159)<-ProblemHandler.handle(ProblemHandler.java:226)<-ProblemReporter.handle(ProblemReporter.java:2393)<-ProblemReporter.i
sClassPathCorrect(ProblemReporter.java:4761)
        -> armeabi/libcordova_hongyun_com_tone_appmain.so (416942 bytes = 407.2 KB)

Small发送运行报错，报错信息如下： 
05-12 10:02:53.252 5368-5368/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: cordova.hongyun.com.tone, PID: 5368
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{cordova.hongyun.com.tone/cordova.hongyun.com.tone.appmain.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.design.widget.CoordinatorLayout
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:472)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                     at cordova.hongyun.com.tone.appmain.MainActivity.onCreate(MainActivity.java:17)
                                                     at android.app.Activity.performCreate(Activity.java:5242)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                     at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:297)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5113) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:597)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:472) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                     at cordova.hongyun.com.tone.appmain.MainActivity.onCreate(MainActivity.java:17) 
                                                     at android.app.Activity.performCreate(Activity.java:5242) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:297) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5113) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.NoClassDefFoundError: android.support.design.R$styleable
                                                     at android.support.design.widget.CoordinatorLayout.<init>(CoordinatorLayout.java:208)
                                                     at android.support.design.widget.CoordinatorLayout.<init>(CoordinatorLayout.java:200)
                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:597) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:472) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                     at cordova.hongyun.com.tone.appmain.MainActivity.onCreate(MainActivity.java:17) 
                                                     at android.app.Activity.performCreate(Activity.java:5242) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                     at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:297) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5113) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515)

Small环境

Compile-time

  gradle-small plugin : 1.2.0-beta4 (maven)
            small aar : 1.2.0-beta4 (maven)
          gradle core : 3.3
       android plugin : 2.3.1
                   OS : Windows 7 6.1 (amd64)

Bundles

| type |   name   |  PP  | sdk |  aapt  | support | file(armeabi) |   size   |
|------|----------|------|-----|--------|---------|---------------|----------|
| host | app      |      | 25  | 25.0.2 | 25.3.1  |               |          |
| app  | app.main | 0x77 | 25  | 25.0.2 | 25.3.1  | *_appmain.so  | 407.2 KB |

**Comment by galenlin** [comment]
你好，请在宿主添加 design 包依赖，在 buildBundle 之前，先 buildLib 。

> 另建议阅读下首页 `贡献指南`，并将issue格式按 `issue模板` 改下

**Comment by liyuhaolol** [comment]
我也遇到这个问题了，按照你们的说法，修改依然无效
