### ISSUE TITLE
java.lang.RuntimeException: Package manager has died

### ISSUE THREAD

**Issue by zhenghuanpeng1992** [wequick/Small#488]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

打包插件后运行宿主

## 你期望的结果是什么？

程序正常

## 实际结果是什么？

```
java.lang.RuntimeException: Package manager has died
                                                                            at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:116)
                                                                            at net.wequick.small.ActivityLauncher.setUp(ActivityLauncher.java:60)
                                                                            at net.wequick.small.Bundle.setupLaunchers(Bundle.java:363)
                                                                            at net.wequick.small.Bundle.loadBundles(Bundle.java:297)
                                                                            at net.wequick.small.Bundle.loadLaunchableBundles(Bundle.java:233)
                                                                            at net.wequick.small.Small.setUp(Small.java:176)
                                                                            at net.wequick.small.Small.setUpOnDemand(Small.java:190)
                                                                            at net.wequick.small.ApkBundleLauncher$ActivityThreadHandlerCallback.ensureServiceClassesLoadable(ApkBundleLauncher.java:193)
                                                                            at net.wequick.small.ApkBundleLauncher$ActivityThreadHandlerCallback.handleMessage(ApkBundleLauncher.java:136)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                            at android.os.Looper.loop(Looper.java:194)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                         Caused by: android.os.TransactionTooLargeException
                                                                            at android.os.BinderProxy.transactNative(Native Method)
                                                                            at android.os.BinderProxy.transact(Binder.java:504)
                                                                            at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:1798)
                                                                            at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:111)
                                                                            at net.wequick.small.ActivityLauncher.setUp(ActivityLauncher.java:60)?
                                                                            at net.wequick.small.Bundle.setupLaunchers(Bundle.java:363)?
                                                                            at net.wequick.small.Bundle.loadBundles(Bundle.java:297)?
                                                                            at net.wequick.small.Bundle.loadLaunchableBundles(Bundle.java:233)?
                                                                            at net.wequick.small.Small.setUp(Small.java:176)?
                                                                            at net.wequick.small.Small.setUpOnDemand(Small.java:190)?
                                                                            at net.wequick.small.ApkBundleLauncher$ActivityThreadHandlerCallback.ensureServiceClassesLoadable(ApkBundleLauncher.java:193)?
                                                                            at net.wequick.small.ApkBundleLauncher$ActivityThreadHandlerCallback.handleMessage(ApkBundleLauncher.java:136)?
                                                                            at android.os.Handler.dispatchMessage(Handler.java:107)?
                                                                            at android.os.Looper.loop(Looper.java:194)?
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5546)?
                                                                            at java.lang.reflect.Method.invoke(Native Method)?
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)?
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)?
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)?
```

### Compile-time

```
gradle-small plugin : 1.2.0-alpha3 (maven)
            small aar : 1.2.0-alpha3 (maven)
          gradle core : 3.3
       android plugin : 2.3.0
                   OS : Mac OS X 10.12.5 (x86_64)
```

### Bundles

| type |          name          |  PP  | sdk |  aapt  | support |     file     |   size   |
|------|------------------------|------|-----|--------|---------|--------------|----------|
| host | app             |      | 25  | 25.0.3 |         |              |          |
| stub | app+stub                   |      | 25  | 25.0.3 |         |              |          |
| app  | app.xxx | 0x30 | 25  | 25.0.3 |         | *.xx.apk | 212.6 KB |
| app  | app.xxx   | 0x40 | 25  | 25.0.3 |         | *.xx.apk   | 440.4 KB |
| lib  | lib.common             | 0x20 | 25  | 25.0.3 |         | *.common.apk | 107.1 KB |

### Runtime

```
  Device : Redmi Note 3
     SDK : Android 5.0.2
     ABI : armeabi-v7a
```

**Comment by zhenghuanpeng1992** [comment]
多个线程同时 PackageManager.getPackageInfo 了吧，造成 binder 进程内存限制炸了

**Comment by galenlin** [comment]
```
net.wequick.small.Small.setUpOnDemand(Small.java:190)?
at net.wequick.small.ApkBundleLauncher$ActivityThreadHandlerCallback.ensureServiceClassesLoadable(ApkBundleLauncher.java:193)
```

从这个log来看，是有其他进程的Service启动了。有多个不同进程的服务吗？你这有没办法分开启动时机试试。

**Comment by galenlin** [comment]
@zhenghuanpeng1992 try `1.2.0-alpha4`

**Comment by zhenghuanpeng1992** [comment]
好的，观察一段时间，这个非必现。

**Comment by rigortek** [comment]
这个连接解析了原因
https://stackoverflow.com/questions/24253976/android-package-manager-has-died-with-transactiontoolargeexception
