### ISSUE TITLE
编译完Sample 运行时出现 java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by whiskeyfei** [wequick/Small#489]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

下载Sample 源代码，更改 
strictSplitResources = false
 buildToAssets = true 
使用命令build lib和budle，运行app。

## 你期望的结果是什么？
正常运行

## 实际结果是什么？

06-06 15:42:33.125 27555-27555/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                       at dalvik.system.DexFile.defineClass(Native Method)
                                                       at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:211)
                                                       at dalvik.system.DexPathList.findClass(DexPathList.java:305)
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:62)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:552)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                       at net.wequick.example.small.app.main.MainActivity.onCreate(MainActivity.java:71)
                                                       at android.app.Activity.performCreate(Activity.java:5128)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                       at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:314)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                       at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
                                                       at dalvik.system.NativeStart.main(Native Method)
### Compile-time

```
 gradle-small plugin : 1.2.0-alpha3 (maven)
            small aar : 1.2.0-alpha3 (maven)
          gradle core : 3.3
       android plugin : 2.3.2
                   OS : Mac OS X 10.11.3 (x86_64)

```

### Bundles

| type |      name      |  PP  | sdk |  aapt  | support |        file         |  size   |
|------|----------------|------|-----|--------|---------|---------------------|---------|
| host | app            |      | 25  | 25.0.2 | 25.1.0  |                     |         |
| stub | app+stub       |      | 25  | 25.0.2 | 25.1.0  |                     |         |
| app  | app.main       | 0x77 | 25  | 25.0.2 | 25.1.0  | *.main.apk          | 11.7 KB |
| app  | app.mine       | 0x16 | 25  | 25.0.2 |         | *.mine.apk          | 47.6 KB |
| app  | app.ok-if-stub | 0x6a | 25  | 25.0.2 |         | *.appok_if_stub.apk | 19.7 KB |
| app  | app.detail     | 0x67 | 25  | 25.0.2 | 25.1.0  | *.detail.apk        | 7.4 KB  |
| app  | app.home       | 0x70 | 25  | 25.0.2 |         | *.home.apk          | 11.3 KB |
| lib  | lib.analytics  | 0x76 | 25  | 25.0.2 |         | *.analytics.apk     | 1.2 MB  |
| lib  | lib.utils      | 0x73 | 25  | 25.0.2 | 25.1.0  | *.utils.apk         | 1.1 MB  |
| lib  | lib.style      | 0x79 | 25  | 25.0.2 | 25.1.0  | *.style.apk         | 1.1 MB  |
| web  | web.about      |      | 25  | 25.0.2 | 25.1.0  | *.about.apk         | 24.3 KB |

### Runtime

```
  Device : i71
     SDK : Android 4.2.2
     ABI : armeabi-v7a
```
谢谢

**Comment by galenlin** [comment]
从反馈来看，你的 `lib.*` 插件的大小都偏大，达到了 1 MB 以上，显然是存在类/资源重复的。
请检查插件依赖，并确认所有插件不包含重复的类与资源。

**Comment by whiskeyfei** [comment]
进行了排查，目前已经可用，谢谢！
