### ISSUE TITLE
样式报错

### ISSUE THREAD

**Issue by whosmyqueen** [wequick/Small#490]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

新建一个项目,新建了app.main和lib.style并提取main里面的样式到style里面

## 你期望的结果是什么？

运行正常

## 实际结果是什么？

```
06-12 17:08:39.657 7635-7635/com.zhph.zhenghaofengqiu E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.zhph.zhenghaofengqiu, PID: 7635
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zhph.zhenghaofengqiu/com.zhph.zhenghaofengqiu.app.main.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:156)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                                         Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:359)
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:328)
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                            at com.zhph.zhenghaofengqiu.app.main.MainActivity.onCreate(MainActivity.java:11)
                                                                            at android.app.Activity.performCreate(Activity.java:6910)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                            at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:314)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:156) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6524) 
```

### Compile-time

```
  gradle-small plugin : 1.2.0-alpha5 (maven)
            small aar : 1.2.0-alpha5 (maven)
          gradle core : 3.3
       android plugin : 2.3.3
                   OS : Mac OS X 10.12.5 (x86_64)
```

### Bundles

| type |   name    |  PP  | sdk |  aapt  | support | file(armeabi) |  size   |
|------|-----------|------|-----|--------|---------|---------------|---------|
| host | app       |      | 25  | 25.0.3 | 25.+    |               |         |
| app  | app.main  | 0x77 | 25  | 25.0.3 | 25.+    | *_main.so     | 15.2 KB |
| lib  | lib.style | 0x79 | 25  | 25.0.3 | 25.+    | *_style.so    | 4.2 KB  |

`项目地址:https://github.com/whosmyqueen/ZHFQ`

### Runtime

```
  Device : 华为P9
     SDK : Android 7.0
     ABI : armeabi
```

**Comment by galenlin** [comment]
调试了半天，发现你 `bundle.json` 里包名写错了。。

https://github.com/whosmyqueen/ZHFQ/blob/master/app/src/main/assets/bundle.json#L10

这里应该是 `xx.lib.style`。

回头我得加个 lint 脚本，把这个代码检查做掉。。

**Comment by whosmyqueen** [comment]
好的

**Comment by whosmyqueen** [comment]
你好   什么时候能解决呢  还是出现这个问题

**Comment by galenlin** [comment]
不是说很明白了，是你的配置问题啊，不是Small的问题
