### ISSUE TITLE
添加的新插件模块，出现R文件报错

### ISSUE THREAD

**Issue by zr940326** [wequick/Small#494]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

由于需求，添加了一个查询模块app.queryAction，单独运行时，是没有问题的，但是用命令gradlew buildBundle -q -Dorg.gradle.parallel=true -Dbundle.minify=true ，就会出现R文件错误

## 你期望的结果是什么？

我希望，赶快解决这个R文件错误，因为通过爬贴，没能解决我的问题

## 实际结果是什么？

  执行gradlew cleanLib -q -Dorg.gradle.parallel=true命令，可以正常运行。
 执行gradlew buildBundle -q -Dorg.gradle.parallel=true -Dbundle.minify=true命令，报如下错误：
——————————————————————————————————————————————
 app.queryAction:generateReleaseSources
:app.queryAction:compileReleaseKotlin
Using kotlin incremental compilation
e: I:\DaZongDSDv\app.queryAction\src\main\java\com\bykj\cq\dazong\direr\appquery\action\MySteelActivity.kt: (42, 24): Unresolved reference: R
e: I:\DaZongDSDv\app.queryAction\src\main\java\com\bykj\cq\dazong\direr\appquery\action\MySteelActivity.kt: (102, 57): Unresolved reference: R
e: I:\DaZongDSDv\app.queryAction\src\main\java\com\bykj\cq\dazong\direr\appquery\action\MySteelActivity.kt: (103, 57): Unresolved reference: R
e: I:\DaZongDSDv\app.queryAction\src\main\java\com\bykj\cq\dazong\direr\appquery\action\MySteelActivity.kt: (104, 57): Unresolved reference: R
:app.queryAction:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app.queryAction:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app.queryAction:compileReleaseKotlin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.GradleException: Compilation error. See log for more details
        at org.jetbrains.kotlin.gradle.tasks.TasksUtilsKt.throwGradleExceptionIfError(tasksUtils.kt:8)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.processCompilerExitCode(Tasks.kt:291)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin_main(Tasks.kt:265)
        at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler$kotlin_gradle_plugin_main(Tasks.kt:163)
        at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:144)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 20 more

BUILD FAILED

——————————————————————————————

### Compile-time

```
  gradle-small plugin : 1.2.0-alpha4 (maven)
            small aar : 1.2.0-alpha4 (maven)
          gradle core : 3.3
       android plugin : 2.3.1
                   OS : Windows 10 10.0 (amd64)
```

### Bundles

| type |      name       |  PP  | sdk |  aapt  | support |       file        |   size   |
|------|-----------------|------|-----|--------|---------|-------------------|----------|
| host | app             |      | 25  | 25.0.2 | 25.1.0  |                   |          |
| stub | app+stub        |      | 25  | 25.0.2 | 25.1.0  |                   |          |
| app  | app.dvmain      | 0x23 | 25  | 25.0.2 | 25.1.0  | *.appdvmain.apk   | 41.2 KB  |
| app  | app.queryAction | 0x6b | 25  | 25.0.2 | 25.1.0  |                   |          |
| lib  | lib.sharelib    | 0x57 | 25  | 25.0.2 | 25.1.0  | *.appsharelib.apk | 176.4 KB |
| lib  | lib.style       | 0x79 | 25  | 25.0.2 | 25.1.0  | *.libstyle.apk    | 37.2 KB  |

BUILD SUCCESSFUL

### Runtime

```
  Device : 华为荣耀8
     SDK : Android 7.0
     ABI : armeabi-v7a
```

**Comment by galenlin** [comment]
经检查，发生本issue的原因为插件 manifest 的 package 与其 build.gradle 中的 applicationId 不匹配导致。
