### ISSUE TITLE
small和第三方SDK growingio冲突

### ISSUE THREAD

**Issue by Mrhejunjie** [wequick/Small#495]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？
在sample项目根gradle里面引入了classpath 'com.growingio.android:vds-gradle-plugin:0.9.105'依赖
在sample项目的app.mine和app.detail的gradle里面都引入依赖 compile 'com.growingio.android:vds-android-agent:0.9.105@aar'和apply plugin: 'com.growingio.android'

growingio的版本0.9.105

## 你期望的结果是什么？
能够正常的编译

## 实际结果是什么？
编译出错

## 错误详情报告
....

* Exception is:
org.gradle.launcher.daemon.client.DaemonConnectionException: Could not dispatch a message to the daemon.
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(DaemonClientConnection.java:68)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(DaemonClientConnection.java:35)
        at org.gradle.launcher.daemon.client.DaemonClientInputForwarder$ForwardTextStreamToConnection.endOfStream(DaemonClientInputForwarder.java:78)
        at org.gradle.launcher.daemon.client.InputForwarder$1.run(InputForwarder.java:95)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:53433'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:121)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(DaemonClientConnection.java:59)
        ... 8 more
Caused by: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
        at sun.nio.ch.SocketDispatcher.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:259)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:247)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:241)
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:119)
        ... 9 more

....

## 错误复现地址
https://github.com/Mrhejunjie/Small

### Compile-time

```
  gradle-small plugin : 1.2.0-alpha5 (maven)
            small aar : 1.2.0-alpha5 (maven)
          gradle core : 3.3
       android plugin : 2.3.0
                   OS : Windows 8.1 6.3 (amd64)
```

### Bundles

| type |      name      |  PP  | sdk |  aapt  | support | file(armeabi)  |   size   |
|------|----------------|------|-----|--------|---------|----------------|----------|
| host | app            |      | 25  | 25.0.2 | 25.1.0  |                |          |
| stub | app+stub       |      | 25  | 25.0.2 | 25.1.0  |                |          |
| app  | app.main       | 0x77 | 25  | 25.0.2 | 25.1.0  | *_main.so      | 11.8 KB  |
| app  | app.mine       | 0x16 | 25  | 25.0.2 |         | *_mine.so      | 161.2 KB |
| app  | app.ok-if-stub | 0x6a | 25  | 25.0.2 |         | *_stub.so      | 19.7 KB  |
| app  | app.detail     | 0x67 | 25  | 25.0.2 | 25.1.0  | *_detail.so    | 130.8 KB |
| app  | app.home       | 0x70 | 25  | 25.0.2 |         | *_home.so      | 11.3 KB  |
| lib  | lib.analytics  | 0x76 | 25  | 25.0.2 |         | *_analytics.so | 126.6 KB |
| lib  | lib.utils      | 0x73 | 25  | 25.0.2 | 25.1.0  | *_utils.so     | 6.8 KB   |
| lib  | lib.style      | 0x79 | 25  | 25.0.2 | 25.1.0  | *_style.so     | 5.5 KB   |
| web  | web.about      |      | 25  | 25.0.2 | 25.1.0  | *_about.so     | 24.5 KB  |

### Runtime

```
  Device : 红米note4x
     SDK : Android 7.0
     ABI : armeabi-v7a
```

**Comment by galenlin** [comment]
我测试了可以正常编译，你编译的命令是什么，贴下。

**Comment by Mrhejunjie** [comment]
编译命令：gradlew buildBundle
你可以拉取我的代码试试

**Comment by galenlin** [comment]
@Mrhejunjie 就是用你的代码编译的，你换个电脑试试，或者用 Mac 试试，看下是不是Windows系统的兼容问题。

**Comment by Mrhejunjie** [comment]
好了，我也编译通过了，多编译几次就可以通过。
