### ISSUE TITLE
java.lang.NoClassDefFoundError: net.wequick.small.BundleParser$R$styleable 

### ISSUE THREAD

**Issue by zhenghuanpeng1992** [wequick/Small#507]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

内置插件发布 App，部分手机报错。

## 你期望的结果是什么？

正常运行

## 实际结果是什么？

```
java.lang.NoClassDefFoundError: net.wequick.small.BundleParser$R$styleable 
at net.wequick.small.BundleParser.parsePackage(BundleParser.java:194) 
at net.wequick.small.BundleParser.parsePackage(BundleParser.java:165) 
at net.wequick.small.BundleParser.parsePackage(BundleParser.java:136) 
at net.wequick.small.ActivityLauncher.setUp(ActivityLauncher.java:58) 
at net.wequick.small.Bundle.setupLaunchers(Bundle.java:363) 
at net.wequick.small.Bundle.loadBundles(Bundle.java:297) 
at net.wequick.small.Bundle.loadLaunchableBundles(Bundle.java:233) 
at net.wequick.small.Small.setUp(Small.java:176) 
at net.wequick.small.Small.setUpOnDemand(Small.java:190) 
at net.wequick.small.ApkBundleLauncher$ActivityThreadHandlerCallback.redirectActivity(ApkBundleLauncher.java:168) 
at net.wequick.small.ApkBundleLauncher$ActivityThreadHandlerCallback.handleMessage(ApkBundleLauncher.java:132) 
at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.
```

### Compile-time

```
  gradle-small plugin : 1.2.0-alpha6 (maven)
            small aar : 1.2.0-alpha6 (maven)
          gradle core : 3.3
       android plugin : 2.3.0
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

|  type  |       name       |   PP   |          file           |    size    |
|--------|------------------|--------|-------------------------|------------|
|  host  |  app             |        |                         |            |
|  app   |  app.default        |  0x77  |  *.default.apk (x86)        |  84.4 KB   |
|  lib   |  lib.common        |  0x16  |  *.common.apk (x86)        |  401.5 KB   |

### Runtime

```
  Device : DOOV-DOOV T20L
     SDK : Android 4.4.4
     ABI : armeabi-v7a
```

**Comment by galenlin** [comment]
`java.lang.NoClassDefFoundError` 通常是别的错误引发的衍生异常，请找下 log 看看是否有其他 Root cause 堆栈错误。

这个问题我这没有碰到过，无法从经验推断。

建议在 Sample 中想办法复现问题，找到必现路径，否则无法继续跟进。

**Comment by changehmf** [comment]
可能是bundle.json里面没有添加路由信息
