### ISSUE TITLE
增加自定义控件的自定义属性buildLib报错

### ISSUE THREAD

**Issue by trisiffer** [wequick/Small#51]
Caused by: java.lang.NullPointerException: Cannot invoke method rightShift() on null object
        at net.wequick.gradle.aapt.CppHexEditor.writeInt(CppHexEditor.groovy:100)
        at net.wequick.gradle.aapt.ArscEditor$_writeTypeList_closure6$_closure15.doCall(ArscEditor.groovy:474)
        at net.wequick.gradle.aapt.ArscEditor$_writeTypeList_closure6.doCall(ArscEditor.groovy:473)
        at net.wequick.gradle.aapt.ArscEditor.writeTypeList(ArscEditor.groovy:466)
        at net.wequick.gradle.aapt.ArscEditor$writeTypeList$5.callCurrent(Unknown Source)
        at net.wequick.gradle.aapt.ArscEditor.writeTable(ArscEditor.groovy:349)
        at net.wequick.gradle.aapt.ArscEditor$writeTable$3.callCurrent(Unknown Source)
        at net.wequick.gradle.aapt.ArscEditor.slice(ArscEditor.groovy:230)
        at net.wequick.gradle.aapt.ArscEditor$slice.call(Unknown Source)
        at net.wequick.gradle.aapt.Aapt.filterPackage(Aapt.groovy:59)
        at net.wequick.gradle.aapt.Aapt$filterPackage$0.call(Unknown Source)
        at net.wequick.gradle.AppPlugin$_hookVariantTask_closure15.doCall(AppPlugin.groovy:331)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:558)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter
.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecute
r.java:61)
        ... 49 more

**Comment by galenlin** [comment]
错误原因：在编排插件自身资源时，排序算法错误导致attr未排在第一位，从而在过滤resources.arsc文件时无法正确匹配，触发异常。

gradle-small:0.3.4已修复
