### ISSUE TITLE
Android O Crash

### ISSUE THREAD

**Issue by poovarasanvasudevan** [wequick/Small#518]
I am Getting this Issue in Android O Emulator ,Prior to android O , Nougat ,Lollipop..etc is Working fine
Issue I am Getting

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                        Process: com.shpt, PID: 3567
                                                        java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.shpt/com.shpt.app.main.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.shpt.app.main.MainActivity" on path: DexPathList[[zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/base.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/lib/x86, /system/lib, /system/vendor/lib]]
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2660)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817)
                                                            at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:156)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6440)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:746)
                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.shpt.app.main.MainActivity" on path: DexPathList[[zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/base.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.shpt-35FwbRqLtS5AOOQntJeDxg==/lib/x86, /system/lib, /system/vendor/lib]]
                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1155)
                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2650)
                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817) 
                                                            at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                            at android.os.Looper.loop(Looper.java:156) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:6440) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:746) 

```

### Runtime

```
  Device : Android Emulator
     SDK : Android 8.0
     ABI : Intel x86
```

**Comment by wilsonssss** [comment]
facing the same issue, only crash on android 8.0 @galenlin 

  Device : Google Pixel XL
     SDK : Android 8.0
      ABI : arm64-v8a

**Comment by xufan** [comment]
try to use the this [branch ](https://github.com/wequick/Small/tree/less-hook-and-reflection)

**Comment by yanmain** [comment]
使用了分支less-hook-and-reflection，会出现so无法加载activity的xml布局文件，找不到id @xufan @galenlin 

Device: google模拟器
SDK: Android 8.0
ABI: x86

**Comment by xufan** [comment]
@yanmain try to add this method hook in ``ApkInstrumentation``
```java
@Override
    public Activity newActivity(ClassLoader cl, String className, Intent intent) throws InstantiationException, IllegalAccessException, ClassNotFoundException {
        Activity activity = mBase.newActivity(cl, className, intent);
        try {
            //api 8.0 
            ReflectAccelerator.setField(ContextThemeWrapper.class, activity, "mResources", Small.getContext().getResources());
        } catch (Exception ignored) {
        }

        return activity;
    }
```

**Comment by zhengxiaopeng** [comment]
@yanmain so 库加载需要重新处理，Or Try [Compact Android O](https://github.com/zhengxiaopeng/Small/tree/android_o_compat)

**Comment by galenlin** [comment]
@poovarasanvasudevan We've accepted @zhengxiaopeng 's PR to resolve this issue, and publish [1.3.0-alpha1](https://github.com/wequick/Small/releases/tag/android-v1.3.0-alpha1).
