### ISSUE TITLE
com.android.support:design 只在布局文件内使用出现崩溃问题

### ISSUE THREAD

**Issue by tianfuchao** [wequick/Small#527]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告
5 18892-18892/cn.qm.mobile.portal.fawtest2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: cn.qm.mobile.portal.fawtest2, PID: 18892
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.qm.mobile.portal.fawtest2/cn.qm.mobile.portal.app.main.QMPortalNewLoginActivity}: android.view.InflateException: Binary XML file line #64: Binary XML file line #64: Error inflating class android.support.design.widget.TextInputLayout
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                               Caused by: android.view.InflateException: Binary XML file line #64: Binary XML file line #64: Error inflating class android.support.design.widget.TextInputLayout
                                                                               Caused by: android.view.InflateException: Binary XML file line #64: Error inflating class android.support.design.widget.TextInputLayout
                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                  at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                  at cn.qm.mobile.portal.app.main.QMPortalNewLoginActivity.onCreate(QMPortalNewLoginActivity.java:75)
                                                                                  at android.app.Activity.performCreate(Activity.java:6662)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                  at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:320)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                  at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                               Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 3: TypedValue{t=0x2/d=0x7f0100b4 a=16}
                                                                                  at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
                                                                                  at android.support.v7.widget.TintTypedArray.getColorStateList(TintTypedArray.java:142)
                                                                                  at android.support.design.widget.CollapsingTextHelper.setCollapsedTextAppearance(CollapsingTextHelper.java:205)
09-14 21:35:11.556 18892-18892/cn.qm.mobile.portal.fawtest2 E/AndroidRuntime:     at android.support.design.widget.TextInputLayout.setHintTextAppearance(TextInputLayout.java:542)
                                                                                  at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:219)
                                                                                  at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:183)
                                                                                  	... 30 more
## 布局文件
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    android:paddingBottom="0dp"
    android:paddingLeft="0dp"
    android:paddingRight="0dp"
    android:paddingTop="0dp"
    android:background="#FFFFFF">

    
    <ImageView
        android:id="@+id/imageView3"
        android:layout_width="match_parent"
        android:layout_height="178dp"
        android:layout_marginBottom="0dp"
        android:layout_marginTop="0dp"
        android:scaleType="centerCrop" />
    <ScrollView
        android:id="@+id/login_form"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fillViewport="true">

        <LinearLayout
            android:id="@+id/email_login_form"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="top"
            android:orientation="vertical"
            android:padding="0dp"
            android:textAlignment="gravity"
            android:weightSum="1">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:gravity="center"
                    android:orientation="vertical">

                    
                </LinearLayout>
            </RelativeLayout>

            <android.support.design.widget.TextInputLayout
                android:id="@+id/name_TextInputLayout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingLeft="10dp"
                android:paddingTop="10dp"
                >

                <AutoCompleteTextView
                    android:id="@+id/email"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:drawableLeft="@drawable/txtmail"
                    android:drawablePadding="10dp"
                    android:hint="@string/prompt_email"
                    android:inputType="textEmailAddress"
                    android:maxLines="1"
                    android:paddingLeft="10dp"
                    android:paddingTop="40dp"
                    android:singleLine="true" />

            </android.support.design.widget.TextInputLayout>

            <android.support.design.widget.TextInputLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingLeft="10dp"
                >

                <EditText
                    android:id="@+id/password"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:drawableLeft="@drawable/txtpwd"
                    android:drawablePadding="10dp"
                    android:hint="@string/prompt_password"
                    android:imeActionId="@+id/login"
                    android:imeActionLabel="@string/action_sign_in_short"
                    android:imeOptions="actionUnspecified"
                    android:inputType="textPassword"
                    android:maxLines="1"
                    android:paddingLeft="10dp"
                    android:singleLine="true" />

            </android.support.design.widget.TextInputLayout>

        </LinearLayout>
    </ScrollView>
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom"
        >

        <Button

            android:id="@+id/email_sign_in_button"
            style="?android:textAppearanceSmall"
            android:layout_width="match_parent"
            android:layout_height="40dp"
            android:layout_marginBottom="20dp"
            android:layout_marginLeft="20dp"
            android:layout_marginRight="20dp"
            android:layout_marginTop="10dp"
            android:layout_weight="0.01"
            android:background="@drawable/dl_btn_shape"

            android:text="登       录"
            android:textColor="#ffffff"
            android:textSize="18dp"
            android:textStyle="bold" />
    </RelativeLayout>

</LinearLayout>

## gradle 配置
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "cn.qm.mobile.portal.app.main"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    aaptOptions {
        additionalParameters '-c', 'zh-rCN'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile "com.android.support:appcompat-v7:$supportLibraryVersion"
    compile "com.android.support:design:$supportLibraryVersion"
    compile "com.android.support:support-vector-drawable:$supportLibraryVersion"
    testCompile 'junit:junit:4.12'

    compile project(path: ':lib.style')
    compile project(path: ':lib.qmclientapi')
    //工具类
    compile project(path: ':lib.utils')
}

## 你做了什么？
- 在布局文件内使用了TextInputLayout，运行出现未知道到类
- 查看编译后的apk main里没有这类
![image](https://user-images.githubusercontent.com/9409701/30461142-83c84598-99ee-11e7-96b2-be4a686016db.png)
- 在引用的lib.utlls 的apk内存在 TextInputLayout
![image](https://user-images.githubusercontent.com/9409701/30461173-f2742020-99ee-11e7-81a2-b6cbd2f35b1b.png)

运行后直接崩溃报此错误

## 你期望的结果是什么？
可正常运行，布局 XML不会出现这种问题

## 实际结果是什么？
运行崩溃，XML 使用引包的组件错误

### Compile-time

```
  gradle-small plugin : 1.2.0-alpha6 (maven)
            small aar : 1.2.0-alpha6 (maven)
          gradle core : 3.3
       android plugin : 2.3.3
                   OS : Mac OS X 10.12.5 (x86_64)
```

### Bundles

| type |      name       |  PP  | sdk |  aapt  | support |       file        |   size   |
|------|-----------------|------|-----|--------|---------|-------------------|----------|
| host | app             |      | 25  | 25.0.3 | 25.3.1  |                   |          |
| stub | app+stub        |      | 25  | 25.0.3 | 25.3.1  |                   |          |
| app  | app.main        | 0x77 | 25  | 25.0.3 | 25.3.1  | *.main.apk        | 22.1 KB  |
| app  | app.contact     | 0x7c | 25  | 25.0.3 | 25.3.1  | *.contact.apk     | 881 KB   |
| lib  | lib.qmdb        | 0x3b | 25  | 25.0.3 |         | *.qmdb.apk        | 625.7 KB |
| lib  | lib.utils       | 0x73 | 25  | 25.0.3 | 25.3.1  | *.utils.apk       | 1.1 MB   |
| lib  | lib.qmclientapi | 0x5f | 25  | 25.0.3 |         | *.qmclientapi.apk | 65.2 KB  |
| lib  | lib.style       | 0x79 | 25  | 25.0.3 | 25.3.1  | *.style.apk       | 1.6 MB   |

### Runtime

```
  Device : Samsung Nexus S
     SDK : Android 7.0
     ABI : armeabi-v7a
```

**Comment by tianfuchao** [comment]
已解决 com.android.support:design 方到app+sub下 建议把所有的com.android.support都放到app+sub

**Comment by galenlin** [comment]
@tianfuchao 是的，Support主题包需要放到宿主(或分身)下。
