### ISSUE TITLE
Error:Execution failed for task ':app.main:preBuild'. > Could not get unknown property 'libraries' for task ':app.main:processDebugManifest' of type com.android.build.gradle.tasks.MergeManifests.

### ISSUE THREAD

**Issue by tangxuesong6** [wequick/Small#542]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

教程第二步,创建一个moddle

## 你期望的结果是什么？

创建成功

## 实际结果是什么？

Error:Execution failed for task ':app.main:preBuild'.
> Could not get unknown property 'libraries' for task ':app.main:processDebugManifest' of type com.android.build.gradle.tasks.MergeManifests.

## Small环境

1.3.0-beta3

### Compile-time

```
  gradle-small plugin : 1.0.0-alpha2 (project)
            small aar : 1.1.0-beta5 (project)
          gradle core : 2.10
       android plugin : 2.0.0
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

|  type  |       name       |   PP   |          file           |    size    |
|--------|------------------|--------|-------------------------|------------|
|  host  |  app             |        |                         |            |
|  app   |  app.main        |  0x77  |  *_main.so (x86)        |  10.9 KB   |
|  app   |  app.mine        |  0x16  |  *_mine.so (x86)        |  35.5 KB   |
|  app   |  app.detail      |  0x67  |  *_detail.so (x86)      |  6.6 KB    |
|  app   |  app.home        |  0x70  |  *_home.so (x86)        |  10.4 KB   |
|  lib   |  lib.afterutils  |  0x45  |  *_afterutils.so (x86)  |  21.2 KB   |
|  lib   |  lib.analytics   |  0x76  |  *_analytics.so (x86)   |  125.7 KB  |
|  lib   |  lib.utils       |  0x73  |  *_utils.so (x86)       |  46 KB     |
|  lib   |  lib.style       |  0x79  |  *_style.so (x86)       |  44.9 KB   |
|  web   |  web.about       |        |  *_about.so (x86)       |  24.3 KB   |

gradle 3.0

```

**Comment by likfe** [comment]
Compile-time
```
  gradle-small plugin : 1.0.0-alpha2 (project)
            small aar : 1.1.0-beta5 (project)
          gradle core : 2.10
       android plugin : 2.0.0
                   OS : Mac OS X 10.12 (x86_64)

**Comment by HysDennis** [comment]
我也碰到同样的问题，请问有什么解决方法

**Comment by HysDennis** [comment]
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app.main:preBuild'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'libraries' for task ':app.main:processDebugManifest' of type com.android.build.gradle.tasks.MergeManifests.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
	at com.android.build.gradle.tasks.MergeManifests_Decorated.getProperty(Unknown Source)
	at net.wequick.gradle.AppPlugin$_hookPreDebugBuild_closure7.doCall(AppPlugin.groovy:229)
	at net.wequick.gradle.AppPlugin.hookPreDebugBuild(AppPlugin.groovy:221)
	at net.wequick.gradle.AndroidPlugin$_afterEvaluate_closure5.doCall(AndroidPlugin.groovy:105)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:681)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 27 more

**Comment by AndroidHensen** [comment]
我也是这个问题，望官方给个说话

**Comment by galenlin** [comment]
git pull 最新的代码试试吧

**Comment by podinns** [comment]
请问解决了吗！

**Comment by galenlin** [comment]
@AndroidHensen @podinns Android Gradle Plugin 先改成 2.3.0

3.0 的适配中，即将支持。

**Comment by Merry-August** [comment]
我也遇到這個問題，然後使用在build.gradle上引用1.5.0版本的Small后就解決了。
在build.gradle：
buildscript  {
    dependencies {
        classpath 'net.wequick.tools.build:gradle-small:1.5.0-beta2'
    }
}

apply plugin: 'net.wequick.small'

small {
    aarVersion = '1.5.0-beta2'
}

具體可參考這個：https://github.com/wequick/Small/tree/master/Android

**Comment by ZhangKuixun** [comment]
> @AndroidHensen @podinns Android Gradle Plugin 先改成 2.3.0
> 3.0 的适配中，即将支持，见 #557
请问适配好了吗？
