### ISSUE TITLE
java.lang.IllegalArgumentException: field android.support.v4.app.TaskStackBuilder.IMPL has type android.support.v4.app.TaskStackBuilder$TaskStackBuilderBaseImpl, got $Proxy0

### ISSUE THREAD

**Issue by 456838** [wequick/Small#547]
W/System.err: java.lang.IllegalArgumentException: field android.support.v4.app.TaskStackBuilder.IMPL has type android.support.v4.app.TaskStackBuilder$TaskStackBuilderBaseImpl, got $Proxy0
11-10 15:47:19.103 30506-30625/com.salton123.sf W/System.err:     at java.lang.reflect.Field.set(Native Method)
11-10 15:47:19.103 30506-30625/com.salton123.sf W/System.err:     at net.wequick.small.ApkBundleLauncher.setUp(ApkBundleLauncher.java:742)
11-10 15:47:19.103 30506-30625/com.salton123.sf W/System.err:     at net.wequick.small.Bundle.setupLaunchers(Bundle.java:363)
11-10 15:47:19.103 30506-30625/com.salton123.sf W/System.err:     at net.wequick.small.Bundle.loadBundles(Bundle.java:297)
11-10 15:47:19.103 30506-30625/com.salton123.sf W/System.err:     at net.wequick.small.Bundle.access$100(Bundle.java:69)
11-10 15:47:19.103 30506-30625/com.salton123.sf W/System.err:     at net.wequick.small.Bundle$LoadBundleThread.run(Bundle.java:744)
11-10 15:47:19.104 30506-30625/com.salton123.sf E/ApkBundleLauncher: Could not find any APK bundles!

# 编译环境
  gradle-small plugin : 1.3.0-beta3 (maven)
            small aar : 1.3.0-beta3 (maven)
          gradle core : 3.3
       android plugin : 2.3.3
                   OS : Windows 7 6.1 (amd64)
```

### Bundles

| type |        name         |  PP  | sdk |  aapt  |    support    | file | size |
|------|---------------------|------|-----|--------|---------------|------|------|
| host | app                 |      | 26  | 26.0.0 |               |      |      |
| stub | app+stub            |      | 26  | 26.0.0 | 26.0.0-alpha1 |      |      |
| app  | app.main            | 0x77 | 26  | 26.0.0 |               |      |      |
| app  | app.wechat          | 0x2b | 26  | 26.0.0 |               |      |      |
| app  | app.flow            | 0x75 | 26  | 26.0.0 |               |      |      |
| app  | app.zhihu           | 0x52 | 26  | 26.0.0 |               |      |      |
| lib  | lib.base            | 0x3c | 26  | 26.0.0 |               |      |      |
| lib  | lib.saltonframework | 0x5d | 26  | 26.0.0 |               |      |      |

## 请问这是什么原因呢？

**Comment by galenlin** [comment]
`Could not find any APK bundles!`

没有编译吧.

先 `buildLib`、`buildBundle` 再运行

**Comment by 456838** [comment]
编译了。我用的support库是26.0.0-alpha1

**Comment by galenlin** [comment]
已经确定问题了，在support 26.0 以上库，该 hook 失效。
将导致使用 `TaskStackBuilder` 创建的 pendingIntent 无法响应点击跳转。

解决方法：使用 `Small.wrapIntent` 手动处理一次意图。
