### ISSUE TITLE
宿主分身资源问题

### ISSUE THREAD

**Issue by zhenghuanpeng1992** [wequick/Small#558]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

## 你做了什么？

宿主分身里下沉了宿主和插件公共的资源，包括 Android Support 的库。当之前版本打出的插件在新版本宿主 App 里运行时会报资源类错误。 
同时我的疑问：这些打进宿主的分身资源没有像 lib 插件那样对资源做固定处理，那么是否是存在这样的问题，每次当宿主里有较多资源变更时导致打出分身里的资源 ID 变了，然后插件里是引用了之前版本的分身里的资源 ID，然后就错了。

## 你期望的结果是什么？

能正常找到处理分身里的公共资源。

## 实际结果是什么？

资源错误。
```
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
                                                                             at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:666)
                                                                             at android.support.design.widget.TabLayout.<init>(TabLayout.java:309)
                                                                             at android.support.design.widget.TabLayout.<init>(TabLayout.java:285)
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                             at com.cardniu.app.loan.ui.LoanMainActivity.onCreate(LoanMainActivity.java:263) 
                                                                             at android.app.Activity.performCreate(Activity.java:6295) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                             at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:333) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2618) 
                                                                             at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                             at android.os.Looper.loop(Looper.java:207) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5701) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769) 
```

### Compile-time

```
  gradle-small plugin : 1.2.0-alpha6 (project)
            small aar : 1.2.0-alpha6 (project)
          gradle core : 3.3
       android plugin : 2.3.0
                   OS : Mac OS X 10.13.1 (x86_64)
```

### Bundles

| type |      name      |  PP  | sdk |  aapt  | support |        file         |  size   |
|------|----------------|------|-----|--------|---------|---------------------|---------|
| host | app            |      | 25  | 25.0.2 | 25.1.0  |                     |         |
| stub | app+stub       |      | 25  | 25.0.2 | 25.1.0  |                     |         |
| app  | app.main       | 0x77 | 25  | 25.0.2 | 25.1.0  | *.main.apk          | 11 KB   |
| app  | app.mine       | 0x16 | 25  | 25.0.2 |         | *.mine.apk          | 46.7 KB |
| app  | app.ok-if-stub | 0x6a | 25  | 25.0.2 |         | *.appok_if_stub.apk | 17.2 KB |
| app  | app.detail     | 0x67 | 25  | 25.0.2 | 25.1.0  | *.detail.apk        | 7.1 KB  |
| app  | app.home       | 0x70 | 25  | 25.0.2 |         | *.home.apk          | 10 KB   |
| lib  | lib.afterutils | 0x45 | 25  | 25.0.2 | 25.1.0  | *.afterutils.apk    | 3.6 KB  |
| lib  | lib.analytics  | 0x76 | 25  | 25.0.2 |         | *.analytics.apk     | 74.4 KB |
| lib  | lib.utils      | 0x73 | 25  | 25.0.2 | 25.1.0  | *.utils.apk         | 6.6 KB  |
| lib  | lib.style      | 0x79 | 25  | 25.0.2 | 25.1.0  | *.style.apk         | 5.4 KB  |
| web  | web.about      |      | 25  | 25.0.2 | 25.1.0  | *.about.apk         | 24.3 KB |

### Runtime

```
  Device : Samsung Nexus S
     SDK : Android 7.0
     ABI : armeabi-v7a
```

**Comment by zhenghuanpeng1992** [comment]
前后两个版本的对应资源属性映射 ID:
```
public static final int[] TabLayout = {
            0x7f01027a, 0x7f01027b, 0x7f01027c, 0x7f01027d,
            0x7f01027e, 0x7f01027f, 0x7f010280, 0x7f010281,
            0x7f010282, 0x7f010283, 0x7f010284, 0x7f010285,
            0x7f010286, 0x7f010287, 0x7f010288, 0x7f010289
        };




public static final int[] TabLayout = {
            0x7f010273, 0x7f010274, 0x7f010275, 0x7f010276,
            0x7f010277, 0x7f010278, 0x7f010279, 0x7f01027a,
            0x7f01027b, 0x7f01027c, 0x7f01027d, 0x7f01027e,
            0x7f01027f, 0x7f010280, 0x7f010281, 0x7f010282
        };
```

**Comment by galenlin** [comment]
分身里的资源现在确实没有做固定处理的，要下沉到分身需要足够稳定。

**Comment by zhenghuanpeng1992** [comment]
@galenlin 开始没注意到这个坑。。。 [文档](http://code.wequick.net/Small/cn/stub-module)里应该加个注意事项：插件里不能出现直接引用分身资源的情况，以免前后几个宿主版本的情况下同一插件可能会出现资源 ID 映射错误的情况，尤其注意下沉到分身里的 Support 库里的资源代码。
