### ISSUE TITLE
 Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f080121

### ISSUE THREAD

**Issue by woyl** [wequick/Small#562]
按到sample来的还是报这个错，，一天都没有解决，，！！！！
 Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f080121
                                                                       at android.content.res.Resources.getValue(Resources.java:1014)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:331)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:189)
                                                                       at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                                       at android.support.design.widget.TabLayout$TabView.<init>(TabLayout.java:1517)
                                                                       at android.support.design.widget.TabLayout.createTabView(TabLayout.java:931)
                                                                       at android.support.design.widget.TabLayout.newTab(TabLayout.java:568)
                                                                       at android.support.design.widget.TabLayout.populateFromPagerAdapter(TabLayout.java:909)
                                                                       at android.support.design.widget.TabLayout.setPagerAdapter(TabLayout.java:900)
                                                                       at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:813)
                                                                       at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:774)
                                                                       at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:752)
                                                                       at com.boerc.app.main.MainActivity.onCreate(MainActivity.java:38)
                                                                       at android.app.Activity.performCreate(Activity.java:5104)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1092)
                                                                       at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:334)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2254) 
                                                                       at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                       at android.os.Looper.loop(Looper.java:137)

**Comment by woyl** [comment]
public class MainActivity extends AppCompatActivity {

    private SectionsPagerAdapter mSectionsPagerAdapter;
    private TabLayout mTabLayout;
    private ViewPager mViewPager;

    private static String[] sUris = new String[] {"home", "mine"};
    private static String[] sTitles = new String[] {"Home", "Mine"};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_mine);
        mViewPager = (ViewPager) findViewById(R.id.container);
        mTabLayout = (TabLayout) findViewById(R.id.tabs);
        mSectionsPagerAdapter = new SectionsPagerAdapter(getSupportFragmentManager(),this);
        mViewPager.setAdapter(mSectionsPagerAdapter);
        mTabLayout.setupWithViewPager(mViewPager);//这句报错
    }
    public class SectionsPagerAdapter extends FragmentPagerAdapter {
        Context context;
        public SectionsPagerAdapter(FragmentManager fm,Context context) {
            super(fm);
            this.context = context;
        }
        @Override
        public Fragment getItem(int position) {

            Fragment fragment = Small.createObject("fragment-v4", sUris[position], MainActivity.this);
            if (fragment == null) {
                fragment = PlaceholderFragment.newInstance(position + 1);
            }
            return fragment;
        }

        @Override
        public int getCount() {
            return sTitles.length;
        }

        @Override
        public CharSequence getPageTitle(int position) {
            return sTitles[position];
        }
    }


    public static class PlaceholderFragment extends Fragment {

        private static final String ARG_SECTION_NUMBER = "section_number";

        public static PlaceholderFragment newInstance(int sectionNumber) {
            PlaceholderFragment fragment = new PlaceholderFragment();
            Bundle args = new Bundle();
            args.putInt(ARG_SECTION_NUMBER, sectionNumber);
            fragment.setArguments(args);
            return fragment;
        }

        public PlaceholderFragment() {
        }

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                 Bundle savedInstanceState) {
            View rootView = inflater.inflate(R.layout.fragment_main, container, false);
            TextView textView = (TextView) rootView.findViewById(R.id.section_label);
            textView.setText(getString(R.string.section_format, getArguments().getInt(ARG_SECTION_NUMBER)));
            return rootView;
        }
    }
}

**Comment by galenlin** [comment]
缺少必要环境，请按照 issue 模板提问
