### ISSUE TITLE
small集成友盟push不能正常使用(application应该怎么用)

### ISSUE THREAD

**Issue by jackdong0224** [wequick/Small#577]
- [x] 我已阅读并理解 **[贡献指南](https://github.com/wequick/Small/blob/master/贡献指南.md)**，严格遵循其约定。

# 错误报告

04-23 13:56:36.513 3724-3764/net.wequick.example.small E/accs.RegisterDO:  buildRegister
                                                                          java.lang.SecurityException: getDeviceId: Neither user 10166 nor current process has android.permission.READ_PHONE_STATE.
                                                                              at android.os.Parcel.readException(Parcel.java:1665)
                                                                              at android.os.Parcel.readException(Parcel.java:1618)
                                                                              at com.android.internal.telephony.IHwTelephony$Stub$Proxy.getUniqueDeviceId(IHwTelephony.java:1383)
                                                                              at android.telephony.HwTelephonyManagerInner.getUniqueDeviceId(HwTelephonyManagerInner.java:982)
                                                                              at android.telephony.HwInnerTelephonyManagerImpl.getUniqueDeviceId(HwInnerTelephonyManagerImpl.java:340)
                                                                              at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:842)
                                                                              at com.taobao.agoo.a.a.c.a(Taobao:95)
                                                                              at com.taobao.agoo.f.onBindApp(Taobao:141)
                                                                              at com.taobao.accs.data.d.a(Taobao:272)
                                                                              at com.taobao.accs.data.d.b(Taobao:143)
                                                                              at com.taobao.accs.data.d.a(Taobao:32)
                                                                              at com.taobao.accs.data.e.run(Taobao:62)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:776)
04-23 13:56:36.514 3724-3835/net.wequick.example.small E/ConnectivityManager.CallbackHandler: callback not found for RELEASED message

## 你做了什么？
gradlew cleanLib -q
gradlew buildLib -q -Dbundle.arch=armeabi
gradlew buildBundle -q -Dbundle.arch=armeabi

使用友盟最新的依赖
/*友盟统计*/
    compile 'com.umeng.sdk:common:latest.integration'
    compile 'com.umeng.sdk:analytics:latest.integration'
    /*友盟统计*/
    /*友盟push*/

    //PushSDK必须依赖基础组件库，所以需要加入对应依赖
    compile 'com.umeng.sdk:common:1.5.0'
//PushSDK必须依赖utdid库，所以需要加入对应依赖
    compile 'com.umeng.sdk:utdid:1.1.5.3'
//PushSDK
    compile 'com.umeng.sdk:push:4.1.0'

## 你期望的结果是什么？
友盟正常注册,统计,push可以正常使用

## 实际结果是什么？
mPushAgent.register方法应该在主进程和channel进程中都被调用

## Small环境

| type |    name    |  PP  | sdk |  aapt  | support | file(armeabi) |  size   |
|------|------------|------|-----|--------|---------|---------------|---------|
| host | app        |      | 26  | 26.0.2 | 25.1.0  |               |         |
| stub | app+stub   |      | 26  | 26.0.2 | 25.1.0  |               |         |
| app  | app.main   | 0x77 | 26  | 26.0.2 | 25.1.0  | *_main.so     | 12 KB   |
| app  | app.mine   | 0x16 | 26  | 26.0.2 | 25.1.0  | *_mine.so     | 7.7 KB  |
| app  | app.detail | 0x67 | 26  | 26.0.2 | 25.1.0  | *_detail.so   | 11.3 KB |
| app  | app.home   | 0x70 | 26  | 26.0.2 | 25.1.0  | *_home.so     | 11.2 KB |
| lib  | lib.utils  | 0x73 | 26  | 26.0.2 | 25.1.0  | *_utils.so    | 2.1 MB  |
| lib  | lib.style  | 0x79 | 26  | 26.0.2 | 25.1.0  | *_style.so    | 28.6 KB |

### Compile-time

```
  gradle-small plugin : 1.0.0-alpha2 (project)
            small aar : 1.1.0-beta5 (project)
          gradle core : 2.10
       android plugin : 2.0.0
                   OS : Mac OS X 10.12 (x86_64)
```

### Bundles

|  type  |       name       |   PP   |          file           |    size    |
|--------|------------------|--------|-------------------------|------------|
|  host  |  app             |        |                         |            |
|  app   |  app.main        |  0x77  |  *_main.so (x86)        |  10.9 KB   |
|  app   |  app.mine        |  0x16  |  *_mine.so (x86)        |  35.5 KB   |
|  app   |  app.detail      |  0x67  |  *_detail.so (x86)      |  6.6 KB    |
|  app   |  app.home        |  0x70  |  *_home.so (x86)        |  10.4 KB   |
|  lib   |  lib.afterutils  |  0x45  |  *_afterutils.so (x86)  |  21.2 KB   |
|  lib   |  lib.analytics   |  0x76  |  *_analytics.so (x86)   |  125.7 KB  |
|  lib   |  lib.utils       |  0x73  |  *_utils.so (x86)       |  46 KB     |
|  lib   |  lib.style       |  0x79  |  *_style.so (x86)       |  44.9 KB   |
|  web   |  web.about       |        |  *_about.so (x86)       |  24.3 KB   |

### Runtime

```
  Device : Samsung Nexus S
     SDK : Android 7.0
     ABI : armeabi-v7a
```

**Comment by galenlin** [comment]
`android.permission.READ_PHONE_STATE` 这个权限要在宿主或者 stub 的 manifest 里声明。
