### ISSUE TITLE
Click link in WebVew Crashed

### ISSUE THREAD

**Issue by Spring-Xu** [wequick/Small#6]
Process: net.wequick.example.small.app.main, PID: 19034
        java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small.app.main/net.wequick.small.webkit.WebActivity}: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258)
            at android.app.ActivityThread.access$800(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5135)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
            at dalvik.system.NativeStart.main(Native Method)
         Caused by: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
            at android.net.Uri.getQueryParameter(Uri.java:1662)
            at net.wequick.small.webkit.WebActivity.onCreate(WebActivity.java:60)
            at android.app.Activity.performCreate(Activity.java:5361)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2163)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2258) 
            at android.app.ActivityThread.access$800(ActivityThread.java:147) 
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211) 
            at android.os.Handler.dispatchMessage(Handler.java:102) 
            at android.os.Looper.loop(Looper.java:136) 
            at android.app.ActivityThread.main(ActivityThread.java:5135) 
            at java.lang.reflect.Method.invokeNative(Native Method) 
            at java.lang.reflect.Method.invoke(Method.java:515) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
            at dalvik.system.NativeStart.main(Native Method) 
       net.wequick.example.small.app.main D/Chrome: TCPSocketLibevent::OnFileReadWriteTimeout(fd=140)

**Comment by galenlin** [comment]
如何操作？

**Comment by Spring-Xu** [comment]
![操作过程](https://github.com/Spring-Xu/ProjectResource/blob/master/ezgif.com-video-to-gif.gif?raw=true)
在这个界面点网页上的closed按钮

**Comment by galenlin** [comment]
OK, I'll try it later.

**Comment by galenlin** [comment]
无法重现，谁碰到这个问题的尝试解决下。
