### ISSUE TITLE
插件中引入aar包，报资源找不到

### ISSUE THREAD

**Issue by ywh10114** [wequick/Small#614]
2019-08-30 15:56:43.107 28699-28699/? E/art: No implementation found for void com.alipay.iot.sdk.log.Logger.nativeLog(java.lang.String, int, java.lang.String) (tried Java_com_alipay_iot_sdk_log_Logger_nativeLog and Java_com_alipay_iot_sdk_log_Logger_nativeLog__Ljava_lang_String_2ILjava_lang_String_2)
2019-08-30 15:56:43.108 28699-28699/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.alipay.iot.unisdkdemo, PID: 28699
    java.lang.UnsatisfiedLinkError: No implementation found for void com.alipay.iot.sdk.log.Logger.nativeLog(java.lang.String, int, java.lang.String) (tried Java_com_alipay_iot_sdk_log_Logger_nativeLog and Java_com_alipay_iot_sdk_log_Logger_nativeLog__Ljava_lang_String_2ILjava_lang_String_2)
        at com.alipay.iot.sdk.log.Logger.nativeLog(Native Method)
        at com.alipay.iot.sdk.log.Logger.e(Logger.java:31)
        at com.alipay.iot.sdk.utils.AlipayIoTLogger.e(AlipayIoTLogger.java:55)
        at com.alipay.iot.sdk.APIManager.<clinit>(APIManager.java:96)
        at com.alipay.iot.app.main.app.MainApplication.iotSDKInit(MainApplication.java:26)
        at com.alipay.iot.app.main.app.MainApplication.onCreate(MainApplication.java:19)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
        at net.wequick.small.ApkBundleLauncher$2.run(ApkBundleLauncher.java:878)
        at net.wequick.small.Bundle$1.run(Bundle.java:833)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6381)
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by ywh10114** [comment]
没有解决方案吗
