### ISSUE TITLE
buildToolsRevision 24.0.0 rc2编译的插件无法工作

### ISSUE THREAD

**Issue by lucifdch** [wequick/Small#75]
最简单的工程包含一个宿主一个插件，两个各有一个AppCompatActivity，版本是com.android.support:appcompat-v7:23.2.1，Small版本是aarVersion = '0.6.0'

FATAL EXCEPTION: main
                                                                               Process: org.lucifd.demo.smalllastdemo, PID: 30152
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{org.lucifd.demo.smalllastdemo/net.wequick.small.A}: android.content.res.Resources$NotFoundException: Resource ID #0x70020000
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5111)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x70020000
                                                                                   at android.content.res.Resources.getValue(Resources.java:1123)
                                                                                   at android.content.res.Resources.loadXmlResourceParser(Resources.java:2303)
                                                                                   at android.content.res.Resources.getLayout(Resources.java:939)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                   at org.lucifd.demo.app.home.HomeActivity.onCreate(HomeActivity.java:11)
                                                                                   at android.app.Activity.performCreate(Activity.java:5231)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                   at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:137)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5111) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596) 
                                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by lucifdch** [comment]
gradle:2.1.0-alpha3
buildToolsVersion "24.0.0 rc2"

**Comment by lucifdch** [comment]
找到问题了，折腾了一下午buildToolsVersion "23.0.1"，不能使用最新的"24.0.0 rc2"，使用就找不到资源。

**Comment by galenlin** [comment]
感谢反馈 近期研究下看看

**Comment by galenlin** [comment]
gradle-small 0.7.0 已解决
