### ISSUE TITLE
混淆后无法运行

### ISSUE THREAD

**Issue by eaglelzy** [wequick/Small#85]
我导入demo可以正常运行，但是在宿主工程打开混淆开关后，就无法运行了，请问混淆要注意什么吗？
```
buildTypes {
        debug {
            minifyEnabled true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
运行后的异常日志：
```
03-30 16:43:33.300 20400-20400/net.wequick.example.small E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.wequick.example.small, PID: 20400
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{net.wequick.example.small/net.wequick.small.A}: java.lang.ClassNotFoundException: Didn't find class "net.wequick.example.small.app.main.MainActivity" on path: DexPathList[[zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_app_detail.so", zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_app_mine.so", zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_app_home.so", zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_app_main.so", zip file "/data/data/net.wequick.example.small/lib/libcom_example_mysmall_lib_style.so", zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_lib_utils.so", zip file "/data/app/net.wequick.example.small-2/base.apk"],nativeLibraryDirectories=[/data/app/net.wequick.example.small-2/lib/arm, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
        at android.app.ActivityThread.access$800(ActivityThread.java:148)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5310)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "net.wequick.example.small.app.main.MainActivity" on path: DexPathList[[zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_app_detail.so", zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_app_mine.so", zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_app_home.so", zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_app_main.so", zip file "/data/data/net.wequick.example.small/lib/libcom_example_mysmall_lib_style.so", zip file "/data/data/net.wequick.example.small/lib/libnet_wequick_example_small_lib_utils.so", zip file "/data/app/net.wequick.example.small-2/base.apk"],nativeLibraryDirectories=[/data/app/net.wequick.example.small-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1088)
        at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.newActivity(Unknown Source)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386) 
        at android.app.ActivityThread.access$800(ActivityThread.java:148) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5310) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 
    	Suppressed: java.lang.NoClassDefFoundError: net.wequick.example.small.app.main.MainActivity
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:321)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        		... 15 more
    	Suppressed: java.lang.ClassNotFoundException: net.wequick.example.small.app.main.MainActivity
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 14 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by galenlin** [comment]
试了下，似乎无法重现额

**Comment by galenlin** [comment]
已支持宿主代码混淆，请更新最新代码，配置混淆如`Sample/app/proguard-rules.pro`：

```bash
# Support Libraries
-dontwarn android.support.**
-keep class android.support.** { *; }
-keep interface android.support.** { *; }

# Small
-keep class net.wequick.small.Small { public *; }
-keep interface net.wequick.small.** { *; }
```

**Comment by a137235** [comment]
为了解构我们一般都很少将代码放到宿主中,所以支持宿主混淆作用不大.插件混淆基本没法使用,lib使用混淆直接报错,而app会将一些公共库重新打包到自己.混淆是减少体积和提高安全性,能不能实现呢？

**Comment by galenlin** [comment]
因为我们要从插件中分离出公共代码，如果要支持混淆，会很麻烦：

1. 混淆时需要所有的类参与，意味着不能前期分离
2. 混淆后包名、类(文件)名面目全非，甚至会额外抽取出一些额外的类(文件)，意味着后期也很难分离

所以这个活很细呀，思路虽然有，但是具体操作起来恐怕没有那么顺利，需要时间。

**Comment by galenlin** [comment]
gradle-small:0.9.0 已支持混淆，关闭本问题

**Comment by gordonpro** [comment]
@galenlin 你好，请问是插件也支持混淆了吗？

**Comment by 601367322** [comment]
FATAL EXCEPTION: main
                                                              Process: com.prance.app, PID: 8018
                                                              android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class com.prance.base.widget.CircleIndicator
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                  at com.prance.base.util.Utils.getInflate(Utils.java:353)
                                                                  at com.prance.base.banner.BannerHolder.<init>(BannerHolder.java:31)
                                                                  at com.prance.app.ui.home.HomeAdapter.onCreate(HomeAdapter.java:17)
                                                                  at com.prance.base.ui.BaseLoadMoreAdapter.onCreateViewHolder(BaseLoadMoreAdapter.java:75)
                                                                  at com.prance.base.ui.BaseLoadMoreAdapter.onCreateViewHolder(BaseLoadMoreAdapter.java:18)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5836)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5060)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at com.prance.base.widget.pull.swipe.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:604)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1197)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at me.imid.swipebacklayout.lib.SwipeBackLayout.onLayout(SwipeBackLayout.java:391)
                                                                  at android.view.View.layout(View.java:17938)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5812)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                              	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.

**Comment by 601367322** [comment]
不开混淆，调试状态下，也会出现问题，我再看看
