### ISSUE TITLE
希望可以支持 通过action uri的方式启动activity

### ISSUE THREAD

**Issue by trisiffer** [wequick/Small#89]
action uri 不用指定具体activity只要接受到相关action 就可以启动，例如打开网页，打开详情，外部app跳转

**Comment by galenlin** [comment]
action已经支持
uri scheme外部跳转暂未支持

**Comment by funyoung** [comment]
web.about运行不起来是和这个功能为支持有关系，是么？
小米note3，崩溃日志如下：

04-08 19:02:22.764 28348-28348/net.wequick.example.small.web.about E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: net.wequick.example.small.web.about, PID: 28348
                                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small.web.about/net.wequick.example.small.web.about.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5549)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
                                                                                         at android.content.ComponentName.<init>(ComponentName.java:77)
                                                                                         at android.content.Intent.<init>(Intent.java:4214)
                                                                                         at net.wequick.small.AssetBundleLauncher.prelaunchBundle(AssetBundleLauncher.java:123)
                                                                                         at net.wequick.small.Bundle.getLaunchableBundle(Bundle.java:248)
                                                                                         at net.wequick.small.Small.openUri(Small.java:257)
                                                                                         at net.wequick.small.Small.openUri(Small.java:241)
                                                                                         at net.wequick.example.small.web.about.MainActivity.onCreate(MainActivity.java:13)
                                                                                         at android.app.Activity.performCreate(Activity.java:5977)
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5549) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
04-08 19:02:24.797 28348-28348/net.wequick.example.small.web.about I/Process: Sending signal. PID: 28348 SIG: 9
04-08 19:02:42.983 28522-28522/net.wequick.example.small.web.about V/SettingsInterface: invalidate [system]: current 143 != cached 0
04-08 19:02:42.984 28522-28522/net.wequick.example.small.web.about D/ActivityThread: hoder:android.app.IActivityManager$ContentProviderHolder@723ddbc,provider,holder.Provider:android.content.ContentProviderProxy@333ce145
04-08 19:02:43.011 28522-28522/net.wequick.example.small.web.about D/ActivityThread: BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{f01fdcb net.wequick.example.small.web.about}}
04-08 19:02:43.011 28522-28522/net.wequick.example.small.web.about V/ActivityThread: Handling launch of ActivityRecord{152f19a8 token=android.os.BinderProxy@1ecf4cc1 {net.wequick.example.small.web.about/net.wequick.example.small.web.about.MainActivity}}
04-08 19:02:43.017 28522-28522/net.wequick.example.small.web.about V/ActivityThread: ActivityRecord{152f19a8 token=android.os.BinderProxy@1ecf4cc1 {net.wequick.example.small.web.about/net.wequick.example.small.web.about.MainActivity}}: app=android.app.Application@3f30aba7, appName=net.wequick.example.small.web.about, pkg=net.wequick.example.small.web.about, comp={net.wequick.example.small.web.about/net.wequick.example.small.web.about.MainActivity}, dir=/data/app/net.wequick.example.small.web.about-1/base.apk
04-08 19:02:43.033 28522-28522/net.wequick.example.small.web.about I/FeatureParser: can't find hennessy.xml in assets/device_features/,it may be in /system/etc/device_features
04-08 19:02:43.040 28522-28522/net.wequick.example.small.web.about D/AndroidRuntime: Shutting down VM
04-08 19:02:43.041 28522-28522/net.wequick.example.small.web.about E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: net.wequick.example.small.web.about, PID: 28522
                                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small.web.about/net.wequick.example.small.web.about.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5549)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
                                                                                         at android.content.ComponentName.<init>(ComponentName.java:77)
                                                                                         at android.content.Intent.<init>(Intent.java:4214)
                                                                                         at net.wequick.small.AssetBundleLauncher.prelaunchBundle(AssetBundleLauncher.java:123)
                                                                                         at net.wequick.small.Bundle.getLaunchableBundle(Bundle.java:248)
                                                                                         at net.wequick.small.Small.openUri(Small.java:257)
                                                                                         at net.wequick.small.Small.openUri(Small.java:241)
                                                                                         at net.wequick.example.small.web.about.MainActivity.onCreate(MainActivity.java:13)
                                                                                         at android.app.Activity.performCreate(Activity.java:5977)
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526) 
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:169) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5549) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
04-08 19:02:46.316 28522-28522/net.wequick.example.small.web.about I/Process: Sending signal. PID: 28522 SIG: 9

**Comment by galenlin** [comment]
@funyoung 那个没关系的，单独运行web.about有点问题，你放宿主跑是OK的

**Comment by gordonpro** [comment]
外部url scheme启动 感觉可以到 宿主里面定义一个 Activity  专门用来处理你的App外部URI启动

```
 <activity android:name=".UriSchemeDispatchActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data
                    android:scheme="my_app" />
            </intent-filter>
        </activity>
```

这样能处理你全部的 my_app 开头的启动

例如  `my_app://host/path_to_name/path2?q=123` 
到了你的指定 UriSchemeDispatchActivity 然后自己定义跳转
