### ISSUE TITLE
运行Small Sample 报错

### ISSUE THREAD

**Issue by xiehello** [wequick/Small#97]
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wequick.example.small/net.wequick.small.A}: java.lang.IllegalArgumentException: expected receiver of type android.app.AppContextImpl, but got android.app.ContextImpl
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2501)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2557)
            at android.app.ActivityThread.access$600(ActivityThread.java:170)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1423)
            at android.os.Handler.dispatchMessage(Handler.java:117)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:6060)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: expected receiver of type android.app.AppContextImpl, but got android.app.ContextImpl
            at java.lang.reflect.Field.setField(Native Method)
            at java.lang.reflect.Field.set(Field.java:588)
            at net.wequick.small.util.ReflectAccelerator.setValue(ReflectAccelerator.java:410)
            at net.wequick.small.util.ReflectAccelerator.setResources(ReflectAccelerator.java:288)
            at net.wequick.small.util.ReflectAccelerator.setResources(ReflectAccelerator.java:249)
            at net.wequick.small.ApkBundleLauncher.ensureAddAssetPath(ApkBundleLauncher.java:510)
            at net.wequick.small.ApkBundleLauncher.access$200(ApkBundleLauncher.java:66)
            at net.wequick.small.ApkBundleLauncher$InstrumentationWrapper.callActivityOnCreate(ApkBundleLauncher.java:139)

**Comment by galenlin** [comment]
@xiehello 手机型号、版本号麻烦发下

**Comment by xiehello** [comment]
手机型号见于附件。




在 2016-04-11 16:21:23，"林光亮" <notifications@github.com> 写道：


@xiehello 手机型号、版本号麻烦发下

**Comment by galenlin** [comment]
看不到附件额

**Comment by galenlin** [comment]
@xiehello 反射修改Resources部分代码有作了修改，请更新small aarVersion至0.9.0，看是否已解决问题

**Comment by h3r3x3** [comment]
三星 Note4 5.1 仍然报错

**Comment by galenlin** [comment]
@xiehello @h3r3x3 新版已采用修改assets方案，请尝试：`small:1.1.0-beta4`
