### ISSUE TITLE
插件中不能显示通知

### ISSUE THREAD

**Issue by Phoon-Think** [wequick/Small#99]
发现一个问题
通过Small.openUri的方式加载插件，插件中不能显示Android通知
而直接运行插件，通知是可以正常展示的
出错代码如下:
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.my.smalltest, PID: 17592
                                                   android.app.RemoteServiceException: Bad notification posted from package com.my.smalltest: Couldn't create icon: StatusBarIcon(pkg=com.my.smalltestuser=0 id=0x77020000 level=0 visible=true num=0 )
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by galenlin** [comment]
@Phoon-Think 由于涉及到跨进程，状态栏（process: `com.android.systemui`）只能访问宿主的资源，而不能访问插件的资源。

这意味着，通知的图标、自定义layout必须在宿主预定义。

如果有谁有更好的方案，欢迎在这里讨论。
